//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 10:32:28 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gdnid2j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 	Departmental Summons Application Message
 * 								Derived from Case.V1.0.CT
 * 								Extension consists of
 * 				a) Record Prefix
 * 				b) Attachment Indicator
 * 				c) Hearing Group ID
 * 				d) Manual Schedule Indicator
 * 				e) Informant Details Object (v1.1)
 * 				f) SOD Details
 * 				g) Offence Details Object
 * 				i) Application Source ID
 * 				j) Hearing Weight
 * 				k) Penalty Weight
 * 				l) Defendant Details Object (v1.1)				              
 * 				m) Motorcycle Indicator           
 * 				n) Vehicle Registration Mark      
 * 				o) Vehicle Registration Mark Digit
 * 				p) Offence Description Object
 * 				q) Interface ID			
 * 				r) DIC Completion Date
 * 				s) Supplement Document Object (DOP History)
 * 			
 * 
 * <p>Java class for DeptSummons.V1.1.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeptSummons.V1.1.CT">
 *   &lt;complexContent>
 *     &lt;extension base="{}Case.V1.0.CT">
 *       &lt;sequence>
 *         &lt;element name="RecordPrefix" type="{}Prefix.V1.2.CT"/>
 *         &lt;element name="AttachmentIndicator" type="{}FieldIndicator.V1.0.CT"/>
 *         &lt;element name="HrngGroupID" type="{}HrngGroupID.V1.0.CT" minOccurs="0"/>
 *         &lt;element name="ManualScheduleIndicator" type="{}FieldIndicator.V1.0.CT"/>
 *         &lt;element name="InformantDetails" type="{}Informant.V1.1.CT"/>
 *         &lt;element name="SODDetails" type="{}SODKey.V1.0.CT"/>
 *         &lt;element name="OffenceDetails" type="{}OffenceDetails.V1.0.CT"/>
 *         &lt;element name="HearingWeight" type="{}HearingWeight.V1.0.CT"/>
 *         &lt;element name="PenaltyWeight" type="{}PenaltyWeight.V1.0.CT"/>
 *         &lt;element name="DefendantDetails" type="{}Defendant.V1.1.CT"/>
 *         &lt;element name="Motorcycle" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/>
 *         &lt;element name="VehicleRegistrationMark" type="{}VehicleRegistrationMark.V1.0.CT" minOccurs="0"/>
 *         &lt;element name="VehicleRegistrationMarkDigit" type="{}VehicleRegistrationMarkDigit.V1.0.CT" minOccurs="0"/>
 *         &lt;element name="OffenceDesc" type="{}OffenceDesc.V1.1.CT"/>
 *         &lt;element name="InterfaceID" type="{}InterfaceID.V1.0.CT"/>
 *         &lt;element name="DICCompletionDate" type="{CCT}Date.CT" minOccurs="0"/>
 *         &lt;element name="SupplementDocument" type="{}SupplementDocument.V1.0.CT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeptSummons.V1.1.CT", propOrder = {
    "recordPrefix",
    "attachmentIndicator",
    "hrngGroupID",
    "manualScheduleIndicator",
    "informantDetails",
    "sodDetails",
    "offenceDetails",
    "hearingWeight",
    "penaltyWeight",
    "defendantDetails",
    "motorcycle",
    "vehicleRegistrationMark",
    "vehicleRegistrationMarkDigit",
    "offenceDesc",
    "interfaceID",
    "dicCompletionDate",
    "supplementDocument"
})
public class DeptSummonsV11CT
    extends CaseV10CT
{

    @XmlElement(name = "RecordPrefix", required = true)
    protected PrefixV12CT recordPrefix;
    @XmlElement(name = "AttachmentIndicator", required = true)
    protected FieldIndicatorV10CT attachmentIndicator;
    @XmlElement(name = "HrngGroupID")
    protected HrngGroupIDV10CT hrngGroupID;
    @XmlElement(name = "ManualScheduleIndicator", required = true)
    protected FieldIndicatorV10CT manualScheduleIndicator;
    @XmlElement(name = "InformantDetails", required = true)
    protected InformantV11CT informantDetails;
    @XmlElement(name = "SODDetails", required = true)
    protected SODKeyV10CT sodDetails;
    @XmlElement(name = "OffenceDetails", required = true)
    protected OffenceDetailsV10CT offenceDetails;
    @XmlElement(name = "HearingWeight", required = true)
    protected HearingWeightV10CT hearingWeight;
    @XmlElement(name = "PenaltyWeight", required = true)
    protected PenaltyWeightV10CT penaltyWeight;
    @XmlElement(name = "DefendantDetails", required = true)
    protected DefendantV11CT defendantDetails;
    @XmlElement(name = "Motorcycle")
    protected FieldIndicatorV10CT motorcycle;
    @XmlElement(name = "VehicleRegistrationMark")
    protected VehicleRegistrationMarkV10CT vehicleRegistrationMark;
    @XmlElement(name = "VehicleRegistrationMarkDigit")
    protected VehicleRegistrationMarkDigitV10CT vehicleRegistrationMarkDigit;
    @XmlElement(name = "OffenceDesc", required = true)
    protected OffenceDescV11CT offenceDesc;
    @XmlElement(name = "InterfaceID", required = true)
    protected InterfaceIDV10CT interfaceID;
    @XmlElement(name = "DICCompletionDate")
    protected DateCT dicCompletionDate;
    @XmlElement(name = "SupplementDocument")
    protected SupplementDocumentV10CT supplementDocument;

    /**
     * Gets the value of the recordPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link PrefixV12CT }
     *     
     */
    public PrefixV12CT getRecordPrefix() {
        return recordPrefix;
    }

    /**
     * Sets the value of the recordPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefixV12CT }
     *     
     */
    public void setRecordPrefix(PrefixV12CT value) {
        this.recordPrefix = value;
    }

    /**
     * Gets the value of the attachmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getAttachmentIndicator() {
        return attachmentIndicator;
    }

    /**
     * Sets the value of the attachmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setAttachmentIndicator(FieldIndicatorV10CT value) {
        this.attachmentIndicator = value;
    }

    /**
     * Gets the value of the hrngGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link HrngGroupIDV10CT }
     *     
     */
    public HrngGroupIDV10CT getHrngGroupID() {
        return hrngGroupID;
    }

    /**
     * Sets the value of the hrngGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link HrngGroupIDV10CT }
     *     
     */
    public void setHrngGroupID(HrngGroupIDV10CT value) {
        this.hrngGroupID = value;
    }

    /**
     * Gets the value of the manualScheduleIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getManualScheduleIndicator() {
        return manualScheduleIndicator;
    }

    /**
     * Sets the value of the manualScheduleIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setManualScheduleIndicator(FieldIndicatorV10CT value) {
        this.manualScheduleIndicator = value;
    }

    /**
     * Gets the value of the informantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InformantV11CT }
     *     
     */
    public InformantV11CT getInformantDetails() {
        return informantDetails;
    }

    /**
     * Sets the value of the informantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformantV11CT }
     *     
     */
    public void setInformantDetails(InformantV11CT value) {
        this.informantDetails = value;
    }

    /**
     * Gets the value of the sodDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SODKeyV10CT }
     *     
     */
    public SODKeyV10CT getSODDetails() {
        return sodDetails;
    }

    /**
     * Sets the value of the sodDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SODKeyV10CT }
     *     
     */
    public void setSODDetails(SODKeyV10CT value) {
        this.sodDetails = value;
    }

    /**
     * Gets the value of the offenceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OffenceDetailsV10CT }
     *     
     */
    public OffenceDetailsV10CT getOffenceDetails() {
        return offenceDetails;
    }

    /**
     * Sets the value of the offenceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffenceDetailsV10CT }
     *     
     */
    public void setOffenceDetails(OffenceDetailsV10CT value) {
        this.offenceDetails = value;
    }

    /**
     * Gets the value of the hearingWeight property.
     * 
     * @return
     *     possible object is
     *     {@link HearingWeightV10CT }
     *     
     */
    public HearingWeightV10CT getHearingWeight() {
        return hearingWeight;
    }

    /**
     * Sets the value of the hearingWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link HearingWeightV10CT }
     *     
     */
    public void setHearingWeight(HearingWeightV10CT value) {
        this.hearingWeight = value;
    }

    /**
     * Gets the value of the penaltyWeight property.
     * 
     * @return
     *     possible object is
     *     {@link PenaltyWeightV10CT }
     *     
     */
    public PenaltyWeightV10CT getPenaltyWeight() {
        return penaltyWeight;
    }

    /**
     * Sets the value of the penaltyWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link PenaltyWeightV10CT }
     *     
     */
    public void setPenaltyWeight(PenaltyWeightV10CT value) {
        this.penaltyWeight = value;
    }

    /**
     * Gets the value of the defendantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DefendantV11CT }
     *     
     */
    public DefendantV11CT getDefendantDetails() {
        return defendantDetails;
    }

    /**
     * Sets the value of the defendantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefendantV11CT }
     *     
     */
    public void setDefendantDetails(DefendantV11CT value) {
        this.defendantDetails = value;
    }

    /**
     * Gets the value of the motorcycle property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getMotorcycle() {
        return motorcycle;
    }

    /**
     * Sets the value of the motorcycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setMotorcycle(FieldIndicatorV10CT value) {
        this.motorcycle = value;
    }

    /**
     * Gets the value of the vehicleRegistrationMark property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleRegistrationMarkV10CT }
     *     
     */
    public VehicleRegistrationMarkV10CT getVehicleRegistrationMark() {
        return vehicleRegistrationMark;
    }

    /**
     * Sets the value of the vehicleRegistrationMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleRegistrationMarkV10CT }
     *     
     */
    public void setVehicleRegistrationMark(VehicleRegistrationMarkV10CT value) {
        this.vehicleRegistrationMark = value;
    }

    /**
     * Gets the value of the vehicleRegistrationMarkDigit property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleRegistrationMarkDigitV10CT }
     *     
     */
    public VehicleRegistrationMarkDigitV10CT getVehicleRegistrationMarkDigit() {
        return vehicleRegistrationMarkDigit;
    }

    /**
     * Sets the value of the vehicleRegistrationMarkDigit property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleRegistrationMarkDigitV10CT }
     *     
     */
    public void setVehicleRegistrationMarkDigit(VehicleRegistrationMarkDigitV10CT value) {
        this.vehicleRegistrationMarkDigit = value;
    }

    /**
     * Gets the value of the offenceDesc property.
     * 
     * @return
     *     possible object is
     *     {@link OffenceDescV11CT }
     *     
     */
    public OffenceDescV11CT getOffenceDesc() {
        return offenceDesc;
    }

    /**
     * Sets the value of the offenceDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffenceDescV11CT }
     *     
     */
    public void setOffenceDesc(OffenceDescV11CT value) {
        this.offenceDesc = value;
    }

    /**
     * Gets the value of the interfaceID property.
     * 
     * @return
     *     possible object is
     *     {@link InterfaceIDV10CT }
     *     
     */
    public InterfaceIDV10CT getInterfaceID() {
        return interfaceID;
    }

    /**
     * Sets the value of the interfaceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterfaceIDV10CT }
     *     
     */
    public void setInterfaceID(InterfaceIDV10CT value) {
        this.interfaceID = value;
    }

    /**
     * Gets the value of the dicCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getDICCompletionDate() {
        return dicCompletionDate;
    }

    /**
     * Sets the value of the dicCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setDICCompletionDate(DateCT value) {
        this.dicCompletionDate = value;
    }

    /**
     * Gets the value of the supplementDocument property.
     * 
     * @return
     *     possible object is
     *     {@link SupplementDocumentV10CT }
     *     
     */
    public SupplementDocumentV10CT getSupplementDocument() {
        return supplementDocument;
    }

    /**
     * Sets the value of the supplementDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplementDocumentV10CT }
     *     
     */
    public void setSupplementDocument(SupplementDocumentV10CT value) {
        this.supplementDocument = value;
    }

}
