//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 05:38:22 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gdsnij2d;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * payment centre that the payment made
 *                 	'35' - ES - Eastern Magistrates' Courts
 *                 	'36' - FL - Fanling Magistrates' Courts
 *                 	'37' - KT - Kwun Tong Magistrates' Courts
 *                 	'40' - KC - Kowloon City Magistrates' Courts
 *                 	'41' - ST - Shatin Magistrates' Courts
 *                 	'42' - TM - Tuen Mun Magistrates' Courts
 *                 	'43' - TW - Tsuen Wan Magistrates' Courts
 *                 	'55' - PP - Public Payment (Electronic Payment)
 *                 	'90' - RF - Refund
 *                 	'91' - IP - Imprisonment
 *             
 * 
 * <p>Java class for PaymentCentre.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentCentre.V1.0.CT"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;restriction base="&lt;CCT&gt;Code.CT"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentCentre.V1.0.CT")
public class PaymentCentreV10CT
    extends CodeCT
{


}
