//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 05:38:22 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gdsnij2d;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * review details consists of 
 *                                a) Case Number Object
 *                                b) Review Internal Number
 *                                c) Filing Date
 *                                d) Applied Party
 *             
 * 
 * <p>Java class for Review.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Review.V1.0.CT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CaseNumber" type="{}CaseNumber.V1.0.CT"/&gt;
 *         &lt;element name="ReviewwInternalNumber" type="{}ReviewInternalNumber.V1.0.CT"/&gt;
 *         &lt;element name="FilingDate" type="{CCT}Date.CT"/&gt;
 *         &lt;element name="AppliedParty" type="{}ReviewAppliedParty.V1.0.CT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Review.V1.0.CT", propOrder = {
    "caseNumber",
    "reviewwInternalNumber",
    "filingDate",
    "appliedParty"
})
public class ReviewV10CT {

    @XmlElement(name = "CaseNumber", required = true)
    protected CaseNumberV10CT caseNumber;
    @XmlElement(name = "ReviewwInternalNumber", required = true)
    protected ReviewInternalNumberV10CT reviewwInternalNumber;
    @XmlElement(name = "FilingDate", required = true)
    protected DateCT filingDate;
    @XmlElement(name = "AppliedParty", required = true)
    protected ReviewAppliedPartyV10CT appliedParty;

    /**
     * Gets the value of the caseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link CaseNumberV10CT }
     *     
     */
    public CaseNumberV10CT getCaseNumber() {
        return caseNumber;
    }

    /**
     * Sets the value of the caseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseNumberV10CT }
     *     
     */
    public void setCaseNumber(CaseNumberV10CT value) {
        this.caseNumber = value;
    }

    /**
     * Gets the value of the reviewwInternalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewInternalNumberV10CT }
     *     
     */
    public ReviewInternalNumberV10CT getReviewwInternalNumber() {
        return reviewwInternalNumber;
    }

    /**
     * Sets the value of the reviewwInternalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewInternalNumberV10CT }
     *     
     */
    public void setReviewwInternalNumber(ReviewInternalNumberV10CT value) {
        this.reviewwInternalNumber = value;
    }

    /**
     * Gets the value of the filingDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getFilingDate() {
        return filingDate;
    }

    /**
     * Sets the value of the filingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setFilingDate(DateCT value) {
        this.filingDate = value;
    }

    /**
     * Gets the value of the appliedParty property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewAppliedPartyV10CT }
     *     
     */
    public ReviewAppliedPartyV10CT getAppliedParty() {
        return appliedParty;
    }

    /**
     * Sets the value of the appliedParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewAppliedPartyV10CT }
     *     
     */
    public void setAppliedParty(ReviewAppliedPartyV10CT value) {
        this.appliedParty = value;
    }

}
