//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:47:35 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccij2d;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * bail/remand details object for charge case 
 *                                consists of
 *                                a) Defendant Sequence Number
 *                                b) Period Type
 *                                c) Bail Form Reference Number (Pol.40 no.)
 *                                d) Surety Sequency Number
 *                                e) Relationship code/free text between defendant and surety
 *                                f) From Date
 *                                g) To Date
 *                                h) Bail Type
 *                                i) Cash Amount
 *                                j) Own/Undertaking Amount
 *                                k) Bail Condition
 *                                l) Report/Remand Location
 *                                m) Report Frequency
 *                                n) Report on Monday Indicator
 *                                o) Report on Tuesday Indicator
 *                                p) Report on Wednesday Indicator
 *                                q) Report on Thursday Indicator
 *                                r) Report on Friday Indicator
 *                                s) Report on Saturday Indicator
 *                                t) Report on Sunday Indicator
 * 			
 * 
 * <p>Java class for BailRemand.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BailRemand.V1.0.CT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DefendantSequenceNumber" type="{}DefendantSequenceNumber.V1.0.CT"/&gt;
 *         &lt;element name="PeriodType" type="{}PeriodType.V1.0.CT"/&gt;
 *         &lt;element name="BailFormReferenceNumber" type="{}BailBookSerialNumber.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="SuretySequenceNumber" type="{}SuretySequenceNumber.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="RelationshipCode" type="{}RelationshipCode.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="RelationshipText" type="{}RelationshipText.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="FromDate" type="{CCT}Date.CT"/&gt;
 *         &lt;element name="ToDate" type="{CCT}Date.CT" minOccurs="0"/&gt;
 *         &lt;element name="BailType" type="{}BailType.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="CashAmount" type="{}Amount.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="OwnUndertakingAmount" type="{}Amount.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="BailCondition" type="{}BailCondition.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportRemandLocation" type="{}ProsecutionDepartmentStation.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportFrequency" type="{}ReportFrequency.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportMondayIndicator" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportTuesdayIndicator" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportWednesdayIndicator" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportThursdayIndicator" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportFridayIndicator" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportSaturdayIndicator" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/&gt;
 *         &lt;element name="ReportSundayIndicator" type="{}FieldIndicator.V1.0.CT" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BailRemand.V1.0.CT", propOrder = {
    "defendantSequenceNumber",
    "periodType",
    "bailFormReferenceNumber",
    "suretySequenceNumber",
    "relationshipCode",
    "relationshipText",
    "fromDate",
    "toDate",
    "bailType",
    "cashAmount",
    "ownUndertakingAmount",
    "bailCondition",
    "reportRemandLocation",
    "reportFrequency",
    "reportMondayIndicator",
    "reportTuesdayIndicator",
    "reportWednesdayIndicator",
    "reportThursdayIndicator",
    "reportFridayIndicator",
    "reportSaturdayIndicator",
    "reportSundayIndicator"
})
public class BailRemandV10CT {

    @XmlElement(name = "DefendantSequenceNumber", required = true)
    protected DefendantSequenceNumberV10CT defendantSequenceNumber;
    @XmlElement(name = "PeriodType", required = true)
    protected PeriodTypeV10CT periodType;
    @XmlElement(name = "BailFormReferenceNumber")
    protected BailBookSerialNumberV10CT bailFormReferenceNumber;
    @XmlElement(name = "SuretySequenceNumber")
    protected SuretySequenceNumberV10CT suretySequenceNumber;
    @XmlElement(name = "RelationshipCode")
    protected RelationshipCodeV10CT relationshipCode;
    @XmlElement(name = "RelationshipText")
    protected RelationshipTextV10CT relationshipText;
    @XmlElement(name = "FromDate", required = true)
    protected DateCT fromDate;
    @XmlElement(name = "ToDate")
    protected DateCT toDate;
    @XmlElement(name = "BailType")
    protected BailTypeV10CT bailType;
    @XmlElement(name = "CashAmount")
    protected AmountV10CT cashAmount;
    @XmlElement(name = "OwnUndertakingAmount")
    protected AmountV10CT ownUndertakingAmount;
    @XmlElement(name = "BailCondition")
    protected BailConditionV10CT bailCondition;
    @XmlElement(name = "ReportRemandLocation")
    protected ProsecutionDepartmentStationV10CT reportRemandLocation;
    @XmlElement(name = "ReportFrequency")
    protected ReportFrequencyV10CT reportFrequency;
    @XmlElement(name = "ReportMondayIndicator")
    protected FieldIndicatorV10CT reportMondayIndicator;
    @XmlElement(name = "ReportTuesdayIndicator")
    protected FieldIndicatorV10CT reportTuesdayIndicator;
    @XmlElement(name = "ReportWednesdayIndicator")
    protected FieldIndicatorV10CT reportWednesdayIndicator;
    @XmlElement(name = "ReportThursdayIndicator")
    protected FieldIndicatorV10CT reportThursdayIndicator;
    @XmlElement(name = "ReportFridayIndicator")
    protected FieldIndicatorV10CT reportFridayIndicator;
    @XmlElement(name = "ReportSaturdayIndicator")
    protected FieldIndicatorV10CT reportSaturdayIndicator;
    @XmlElement(name = "ReportSundayIndicator")
    protected FieldIndicatorV10CT reportSundayIndicator;

    /**
     * Gets the value of the defendantSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link DefendantSequenceNumberV10CT }
     *     
     */
    public DefendantSequenceNumberV10CT getDefendantSequenceNumber() {
        return defendantSequenceNumber;
    }

    /**
     * Sets the value of the defendantSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefendantSequenceNumberV10CT }
     *     
     */
    public void setDefendantSequenceNumber(DefendantSequenceNumberV10CT value) {
        this.defendantSequenceNumber = value;
    }

    /**
     * Gets the value of the periodType property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodTypeV10CT }
     *     
     */
    public PeriodTypeV10CT getPeriodType() {
        return periodType;
    }

    /**
     * Sets the value of the periodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodTypeV10CT }
     *     
     */
    public void setPeriodType(PeriodTypeV10CT value) {
        this.periodType = value;
    }

    /**
     * Gets the value of the bailFormReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BailBookSerialNumberV10CT }
     *     
     */
    public BailBookSerialNumberV10CT getBailFormReferenceNumber() {
        return bailFormReferenceNumber;
    }

    /**
     * Sets the value of the bailFormReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BailBookSerialNumberV10CT }
     *     
     */
    public void setBailFormReferenceNumber(BailBookSerialNumberV10CT value) {
        this.bailFormReferenceNumber = value;
    }

    /**
     * Gets the value of the suretySequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link SuretySequenceNumberV10CT }
     *     
     */
    public SuretySequenceNumberV10CT getSuretySequenceNumber() {
        return suretySequenceNumber;
    }

    /**
     * Sets the value of the suretySequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuretySequenceNumberV10CT }
     *     
     */
    public void setSuretySequenceNumber(SuretySequenceNumberV10CT value) {
        this.suretySequenceNumber = value;
    }

    /**
     * Gets the value of the relationshipCode property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipCodeV10CT }
     *     
     */
    public RelationshipCodeV10CT getRelationshipCode() {
        return relationshipCode;
    }

    /**
     * Sets the value of the relationshipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipCodeV10CT }
     *     
     */
    public void setRelationshipCode(RelationshipCodeV10CT value) {
        this.relationshipCode = value;
    }

    /**
     * Gets the value of the relationshipText property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipTextV10CT }
     *     
     */
    public RelationshipTextV10CT getRelationshipText() {
        return relationshipText;
    }

    /**
     * Sets the value of the relationshipText property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipTextV10CT }
     *     
     */
    public void setRelationshipText(RelationshipTextV10CT value) {
        this.relationshipText = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setFromDate(DateCT value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setToDate(DateCT value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the bailType property.
     * 
     * @return
     *     possible object is
     *     {@link BailTypeV10CT }
     *     
     */
    public BailTypeV10CT getBailType() {
        return bailType;
    }

    /**
     * Sets the value of the bailType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BailTypeV10CT }
     *     
     */
    public void setBailType(BailTypeV10CT value) {
        this.bailType = value;
    }

    /**
     * Gets the value of the cashAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountV10CT }
     *     
     */
    public AmountV10CT getCashAmount() {
        return cashAmount;
    }

    /**
     * Sets the value of the cashAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountV10CT }
     *     
     */
    public void setCashAmount(AmountV10CT value) {
        this.cashAmount = value;
    }

    /**
     * Gets the value of the ownUndertakingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountV10CT }
     *     
     */
    public AmountV10CT getOwnUndertakingAmount() {
        return ownUndertakingAmount;
    }

    /**
     * Sets the value of the ownUndertakingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountV10CT }
     *     
     */
    public void setOwnUndertakingAmount(AmountV10CT value) {
        this.ownUndertakingAmount = value;
    }

    /**
     * Gets the value of the bailCondition property.
     * 
     * @return
     *     possible object is
     *     {@link BailConditionV10CT }
     *     
     */
    public BailConditionV10CT getBailCondition() {
        return bailCondition;
    }

    /**
     * Sets the value of the bailCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BailConditionV10CT }
     *     
     */
    public void setBailCondition(BailConditionV10CT value) {
        this.bailCondition = value;
    }

    /**
     * Gets the value of the reportRemandLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ProsecutionDepartmentStationV10CT }
     *     
     */
    public ProsecutionDepartmentStationV10CT getReportRemandLocation() {
        return reportRemandLocation;
    }

    /**
     * Sets the value of the reportRemandLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProsecutionDepartmentStationV10CT }
     *     
     */
    public void setReportRemandLocation(ProsecutionDepartmentStationV10CT value) {
        this.reportRemandLocation = value;
    }

    /**
     * Gets the value of the reportFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link ReportFrequencyV10CT }
     *     
     */
    public ReportFrequencyV10CT getReportFrequency() {
        return reportFrequency;
    }

    /**
     * Sets the value of the reportFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportFrequencyV10CT }
     *     
     */
    public void setReportFrequency(ReportFrequencyV10CT value) {
        this.reportFrequency = value;
    }

    /**
     * Gets the value of the reportMondayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getReportMondayIndicator() {
        return reportMondayIndicator;
    }

    /**
     * Sets the value of the reportMondayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setReportMondayIndicator(FieldIndicatorV10CT value) {
        this.reportMondayIndicator = value;
    }

    /**
     * Gets the value of the reportTuesdayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getReportTuesdayIndicator() {
        return reportTuesdayIndicator;
    }

    /**
     * Sets the value of the reportTuesdayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setReportTuesdayIndicator(FieldIndicatorV10CT value) {
        this.reportTuesdayIndicator = value;
    }

    /**
     * Gets the value of the reportWednesdayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getReportWednesdayIndicator() {
        return reportWednesdayIndicator;
    }

    /**
     * Sets the value of the reportWednesdayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setReportWednesdayIndicator(FieldIndicatorV10CT value) {
        this.reportWednesdayIndicator = value;
    }

    /**
     * Gets the value of the reportThursdayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getReportThursdayIndicator() {
        return reportThursdayIndicator;
    }

    /**
     * Sets the value of the reportThursdayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setReportThursdayIndicator(FieldIndicatorV10CT value) {
        this.reportThursdayIndicator = value;
    }

    /**
     * Gets the value of the reportFridayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getReportFridayIndicator() {
        return reportFridayIndicator;
    }

    /**
     * Sets the value of the reportFridayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setReportFridayIndicator(FieldIndicatorV10CT value) {
        this.reportFridayIndicator = value;
    }

    /**
     * Gets the value of the reportSaturdayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getReportSaturdayIndicator() {
        return reportSaturdayIndicator;
    }

    /**
     * Sets the value of the reportSaturdayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setReportSaturdayIndicator(FieldIndicatorV10CT value) {
        this.reportSaturdayIndicator = value;
    }

    /**
     * Gets the value of the reportSundayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getReportSundayIndicator() {
        return reportSundayIndicator;
    }

    /**
     * Sets the value of the reportSundayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setReportSundayIndicator(FieldIndicatorV10CT value) {
        this.reportSundayIndicator = value;
    }

}
