//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:47:35 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccij2d;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * defendant details object for charge case 
 *                                derives from Defendant (V1.3)
 *                                extension consists of
 *                                a) Defendant Sequence Number
 *                                b) Offence Sequence Number
 * 			
 * 
 * <p>Java class for ChargeCaseDefendant.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChargeCaseDefendant.V1.0.CT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}Defendant.V1.3.CT"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DefendantSequenceNumber" type="{}DefendantSequenceNumber.V1.0.CT"/&gt;
 *         &lt;element name="OffenceSequenceNumber" type="{}OffenceSequenceNumber.V1.0.CT" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChargeCaseDefendant.V1.0.CT", propOrder = {
    "defendantSequenceNumber",
    "offenceSequenceNumber"
})
public class ChargeCaseDefendantV10CT
    extends DefendantV13CT
{

    @XmlElement(name = "DefendantSequenceNumber", required = true)
    protected DefendantSequenceNumberV10CT defendantSequenceNumber;
    @XmlElement(name = "OffenceSequenceNumber", required = true)
    protected List<OffenceSequenceNumberV10CT> offenceSequenceNumber;

    /**
     * Gets the value of the defendantSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link DefendantSequenceNumberV10CT }
     *     
     */
    public DefendantSequenceNumberV10CT getDefendantSequenceNumber() {
        return defendantSequenceNumber;
    }

    /**
     * Sets the value of the defendantSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefendantSequenceNumberV10CT }
     *     
     */
    public void setDefendantSequenceNumber(DefendantSequenceNumberV10CT value) {
        this.defendantSequenceNumber = value;
    }

    /**
     * Gets the value of the offenceSequenceNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offenceSequenceNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffenceSequenceNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OffenceSequenceNumberV10CT }
     * 
     * 
     */
    public List<OffenceSequenceNumberV10CT> getOffenceSequenceNumber() {
        if (offenceSequenceNumber == null) {
            offenceSequenceNumber = new ArrayList<OffenceSequenceNumberV10CT>();
        }
        return this.offenceSequenceNumber;
    }

}
