//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:47:35 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccij2d;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hk.judiciary.icmsint.model.sysinf.inf.gccij2d package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hk.judiciary.icmsint.model.sysinf.inf.gccij2d
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GCCIMsgJ2D }
     * 
     */
    public GCCIMsgJ2D createGCCIMsgJ2D() {
        return new GCCIMsgJ2D();
    }

    /**
     * Create an instance of {@link InterfaceFileHeaderV13CT }
     * 
     */
    public InterfaceFileHeaderV13CT createInterfaceFileHeaderV13CT() {
        return new InterfaceFileHeaderV13CT();
    }

    /**
     * Create an instance of {@link ChargeCaseAllocationV10CT }
     * 
     */
    public ChargeCaseAllocationV10CT createChargeCaseAllocationV10CT() {
        return new ChargeCaseAllocationV10CT();
    }

    /**
     * Create an instance of {@link CaseDocumentAcknowledgementV10CT }
     * 
     */
    public CaseDocumentAcknowledgementV10CT createCaseDocumentAcknowledgementV10CT() {
        return new CaseDocumentAcknowledgementV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseAmendmentResultV10CT }
     * 
     */
    public ChargeCaseAmendmentResultV10CT createChargeCaseAmendmentResultV10CT() {
        return new ChargeCaseAmendmentResultV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseHearingResultV10CT }
     * 
     */
    public ChargeCaseHearingResultV10CT createChargeCaseHearingResultV10CT() {
        return new ChargeCaseHearingResultV10CT();
    }

    /**
     * Create an instance of {@link NextHearingV20CT }
     * 
     */
    public NextHearingV20CT createNextHearingV20CT() {
        return new NextHearingV20CT();
    }

    /**
     * Create an instance of {@link WitnessSummonsAllocationV20CT }
     * 
     */
    public WitnessSummonsAllocationV20CT createWitnessSummonsAllocationV20CT() {
        return new WitnessSummonsAllocationV20CT();
    }

    /**
     * Create an instance of {@link CourtDocumentV10CT }
     * 
     */
    public CourtDocumentV10CT createCourtDocumentV10CT() {
        return new CourtDocumentV10CT();
    }

    /**
     * Create an instance of {@link PartyV10CT }
     * 
     */
    public PartyV10CT createPartyV10CT() {
        return new PartyV10CT();
    }

    /**
     * Create an instance of {@link PartyV11CT }
     * 
     */
    public PartyV11CT createPartyV11CT() {
        return new PartyV11CT();
    }

    /**
     * Create an instance of {@link PartyV12CT }
     * 
     */
    public PartyV12CT createPartyV12CT() {
        return new PartyV12CT();
    }

    /**
     * Create an instance of {@link PartyEnglishNameV10CT }
     * 
     */
    public PartyEnglishNameV10CT createPartyEnglishNameV10CT() {
        return new PartyEnglishNameV10CT();
    }

    /**
     * Create an instance of {@link PartyChineseNameV10CT }
     * 
     */
    public PartyChineseNameV10CT createPartyChineseNameV10CT() {
        return new PartyChineseNameV10CT();
    }

    /**
     * Create an instance of {@link PartyChineseNameV11CT }
     * 
     */
    public PartyChineseNameV11CT createPartyChineseNameV11CT() {
        return new PartyChineseNameV11CT();
    }

    /**
     * Create an instance of {@link PartyEnglishSurnameV10CT }
     * 
     */
    public PartyEnglishSurnameV10CT createPartyEnglishSurnameV10CT() {
        return new PartyEnglishSurnameV10CT();
    }

    /**
     * Create an instance of {@link PartyEnglishGivenNameV10CT }
     * 
     */
    public PartyEnglishGivenNameV10CT createPartyEnglishGivenNameV10CT() {
        return new PartyEnglishGivenNameV10CT();
    }

    /**
     * Create an instance of {@link PartyChineseSurnameV10CT }
     * 
     */
    public PartyChineseSurnameV10CT createPartyChineseSurnameV10CT() {
        return new PartyChineseSurnameV10CT();
    }

    /**
     * Create an instance of {@link PartyChineseGivenNameV10CT }
     * 
     */
    public PartyChineseGivenNameV10CT createPartyChineseGivenNameV10CT() {
        return new PartyChineseGivenNameV10CT();
    }

    /**
     * Create an instance of {@link IdentificationTypeV10CT }
     * 
     */
    public IdentificationTypeV10CT createIdentificationTypeV10CT() {
        return new IdentificationTypeV10CT();
    }

    /**
     * Create an instance of {@link IdentificationNumberV10CT }
     * 
     */
    public IdentificationNumberV10CT createIdentificationNumberV10CT() {
        return new IdentificationNumberV10CT();
    }

    /**
     * Create an instance of {@link IdentificationNumberV11CT }
     * 
     */
    public IdentificationNumberV11CT createIdentificationNumberV11CT() {
        return new IdentificationNumberV11CT();
    }

    /**
     * Create an instance of {@link IDNumberTypeV10CT }
     * 
     */
    public IDNumberTypeV10CT createIDNumberTypeV10CT() {
        return new IDNumberTypeV10CT();
    }

    /**
     * Create an instance of {@link OtherIDNumberV10CT }
     * 
     */
    public OtherIDNumberV10CT createOtherIDNumberV10CT() {
        return new OtherIDNumberV10CT();
    }

    /**
     * Create an instance of {@link AgeV10CT }
     * 
     */
    public AgeV10CT createAgeV10CT() {
        return new AgeV10CT();
    }

    /**
     * Create an instance of {@link AgeV11CT }
     * 
     */
    public AgeV11CT createAgeV11CT() {
        return new AgeV11CT();
    }

    /**
     * Create an instance of {@link PhoneNumberV10CT }
     * 
     */
    public PhoneNumberV10CT createPhoneNumberV10CT() {
        return new PhoneNumberV10CT();
    }

    /**
     * Create an instance of {@link PhoneNumberV11CT }
     * 
     */
    public PhoneNumberV11CT createPhoneNumberV11CT() {
        return new PhoneNumberV11CT();
    }

    /**
     * Create an instance of {@link EmailV10CT }
     * 
     */
    public EmailV10CT createEmailV10CT() {
        return new EmailV10CT();
    }

    /**
     * Create an instance of {@link StaffNumberV10CT }
     * 
     */
    public StaffNumberV10CT createStaffNumberV10CT() {
        return new StaffNumberV10CT();
    }

    /**
     * Create an instance of {@link CaseNumberV10CT }
     * 
     */
    public CaseNumberV10CT createCaseNumberV10CT() {
        return new CaseNumberV10CT();
    }

    /**
     * Create an instance of {@link CourtSysV10CT }
     * 
     */
    public CourtSysV10CT createCourtSysV10CT() {
        return new CourtSysV10CT();
    }

    /**
     * Create an instance of {@link CaseTypeV10CT }
     * 
     */
    public CaseTypeV10CT createCaseTypeV10CT() {
        return new CaseTypeV10CT();
    }

    /**
     * Create an instance of {@link CaseSerialNumberV10CT }
     * 
     */
    public CaseSerialNumberV10CT createCaseSerialNumberV10CT() {
        return new CaseSerialNumberV10CT();
    }

    /**
     * Create an instance of {@link CaseYearV10CT }
     * 
     */
    public CaseYearV10CT createCaseYearV10CT() {
        return new CaseYearV10CT();
    }

    /**
     * Create an instance of {@link HearingDetailV10CT }
     * 
     */
    public HearingDetailV10CT createHearingDetailV10CT() {
        return new HearingDetailV10CT();
    }

    /**
     * Create an instance of {@link HearingInternalNumberV10CT }
     * 
     */
    public HearingInternalNumberV10CT createHearingInternalNumberV10CT() {
        return new HearingInternalNumberV10CT();
    }

    /**
     * Create an instance of {@link HearingCourtNumberV10CT }
     * 
     */
    public HearingCourtNumberV10CT createHearingCourtNumberV10CT() {
        return new HearingCourtNumberV10CT();
    }

    /**
     * Create an instance of {@link HearingCourtNumberV11CT }
     * 
     */
    public HearingCourtNumberV11CT createHearingCourtNumberV11CT() {
        return new HearingCourtNumberV11CT();
    }

    /**
     * Create an instance of {@link HearingTypeV10CT }
     * 
     */
    public HearingTypeV10CT createHearingTypeV10CT() {
        return new HearingTypeV10CT();
    }

    /**
     * Create an instance of {@link HearingMagistrateCodeV10CT }
     * 
     */
    public HearingMagistrateCodeV10CT createHearingMagistrateCodeV10CT() {
        return new HearingMagistrateCodeV10CT();
    }

    /**
     * Create an instance of {@link HearingMagistrateCodeV11CT }
     * 
     */
    public HearingMagistrateCodeV11CT createHearingMagistrateCodeV11CT() {
        return new HearingMagistrateCodeV11CT();
    }

    /**
     * Create an instance of {@link LanguageV10CT }
     * 
     */
    public LanguageV10CT createLanguageV10CT() {
        return new LanguageV10CT();
    }

    /**
     * Create an instance of {@link LanguageV11CT }
     * 
     */
    public LanguageV11CT createLanguageV11CT() {
        return new LanguageV11CT();
    }

    /**
     * Create an instance of {@link BasicSequenceNumberV10CT }
     * 
     */
    public BasicSequenceNumberV10CT createBasicSequenceNumberV10CT() {
        return new BasicSequenceNumberV10CT();
    }

    /**
     * Create an instance of {@link OffenceSequenceNumberV10CT }
     * 
     */
    public OffenceSequenceNumberV10CT createOffenceSequenceNumberV10CT() {
        return new OffenceSequenceNumberV10CT();
    }

    /**
     * Create an instance of {@link DefendantSequenceNumberV10CT }
     * 
     */
    public DefendantSequenceNumberV10CT createDefendantSequenceNumberV10CT() {
        return new DefendantSequenceNumberV10CT();
    }

    /**
     * Create an instance of {@link WitnessSequenceNumberV10CT }
     * 
     */
    public WitnessSequenceNumberV10CT createWitnessSequenceNumberV10CT() {
        return new WitnessSequenceNumberV10CT();
    }

    /**
     * Create an instance of {@link SuretySequenceNumberV10CT }
     * 
     */
    public SuretySequenceNumberV10CT createSuretySequenceNumberV10CT() {
        return new SuretySequenceNumberV10CT();
    }

    /**
     * Create an instance of {@link BailRemandIdentifierV10CT }
     * 
     */
    public BailRemandIdentifierV10CT createBailRemandIdentifierV10CT() {
        return new BailRemandIdentifierV10CT();
    }

    /**
     * Create an instance of {@link AddressV10CT }
     * 
     */
    public AddressV10CT createAddressV10CT() {
        return new AddressV10CT();
    }

    /**
     * Create an instance of {@link AddressV11CT }
     * 
     */
    public AddressV11CT createAddressV11CT() {
        return new AddressV11CT();
    }

    /**
     * Create an instance of {@link AddressV12CT }
     * 
     */
    public AddressV12CT createAddressV12CT() {
        return new AddressV12CT();
    }

    /**
     * Create an instance of {@link AddressTerritoryV10CT }
     * 
     */
    public AddressTerritoryV10CT createAddressTerritoryV10CT() {
        return new AddressTerritoryV10CT();
    }

    /**
     * Create an instance of {@link EnglishAddressV10CT }
     * 
     */
    public EnglishAddressV10CT createEnglishAddressV10CT() {
        return new EnglishAddressV10CT();
    }

    /**
     * Create an instance of {@link EnglishAddressV11CT }
     * 
     */
    public EnglishAddressV11CT createEnglishAddressV11CT() {
        return new EnglishAddressV11CT();
    }

    /**
     * Create an instance of {@link EnglishAddressV12CT }
     * 
     */
    public EnglishAddressV12CT createEnglishAddressV12CT() {
        return new EnglishAddressV12CT();
    }

    /**
     * Create an instance of {@link ChineseAddressV10CT }
     * 
     */
    public ChineseAddressV10CT createChineseAddressV10CT() {
        return new ChineseAddressV10CT();
    }

    /**
     * Create an instance of {@link ChineseAddressV11CT }
     * 
     */
    public ChineseAddressV11CT createChineseAddressV11CT() {
        return new ChineseAddressV11CT();
    }

    /**
     * Create an instance of {@link ChineseAddressV12CT }
     * 
     */
    public ChineseAddressV12CT createChineseAddressV12CT() {
        return new ChineseAddressV12CT();
    }

    /**
     * Create an instance of {@link AddressLineV10CT }
     * 
     */
    public AddressLineV10CT createAddressLineV10CT() {
        return new AddressLineV10CT();
    }

    /**
     * Create an instance of {@link EnglishAddressLineV11CT }
     * 
     */
    public EnglishAddressLineV11CT createEnglishAddressLineV11CT() {
        return new EnglishAddressLineV11CT();
    }

    /**
     * Create an instance of {@link ChineseAddressLineV11CT }
     * 
     */
    public ChineseAddressLineV11CT createChineseAddressLineV11CT() {
        return new ChineseAddressLineV11CT();
    }

    /**
     * Create an instance of {@link DistrictCodeV10CT }
     * 
     */
    public DistrictCodeV10CT createDistrictCodeV10CT() {
        return new DistrictCodeV10CT();
    }

    /**
     * Create an instance of {@link CaseV10CT }
     * 
     */
    public CaseV10CT createCaseV10CT() {
        return new CaseV10CT();
    }

    /**
     * Create an instance of {@link ProsecutionDepartmentCodeV10CT }
     * 
     */
    public ProsecutionDepartmentCodeV10CT createProsecutionDepartmentCodeV10CT() {
        return new ProsecutionDepartmentCodeV10CT();
    }

    /**
     * Create an instance of {@link ProsecutionDepartmentCodeV11CT }
     * 
     */
    public ProsecutionDepartmentCodeV11CT createProsecutionDepartmentCodeV11CT() {
        return new ProsecutionDepartmentCodeV11CT();
    }

    /**
     * Create an instance of {@link DepartmentReferenceNumberV10CT }
     * 
     */
    public DepartmentReferenceNumberV10CT createDepartmentReferenceNumberV10CT() {
        return new DepartmentReferenceNumberV10CT();
    }

    /**
     * Create an instance of {@link ProsecutionDepartmentUnitV10CT }
     * 
     */
    public ProsecutionDepartmentUnitV10CT createProsecutionDepartmentUnitV10CT() {
        return new ProsecutionDepartmentUnitV10CT();
    }

    /**
     * Create an instance of {@link ProsecutionDepartmentStationV10CT }
     * 
     */
    public ProsecutionDepartmentStationV10CT createProsecutionDepartmentStationV10CT() {
        return new ProsecutionDepartmentStationV10CT();
    }

    /**
     * Create an instance of {@link DefendantV10CT }
     * 
     */
    public DefendantV10CT createDefendantV10CT() {
        return new DefendantV10CT();
    }

    /**
     * Create an instance of {@link DefendantV11CT }
     * 
     */
    public DefendantV11CT createDefendantV11CT() {
        return new DefendantV11CT();
    }

    /**
     * Create an instance of {@link DefendantV12CT }
     * 
     */
    public DefendantV12CT createDefendantV12CT() {
        return new DefendantV12CT();
    }

    /**
     * Create an instance of {@link DefendantV13CT }
     * 
     */
    public DefendantV13CT createDefendantV13CT() {
        return new DefendantV13CT();
    }

    /**
     * Create an instance of {@link DefendantTypeV10CT }
     * 
     */
    public DefendantTypeV10CT createDefendantTypeV10CT() {
        return new DefendantTypeV10CT();
    }

    /**
     * Create an instance of {@link BailiffDistrictCodeV10CT }
     * 
     */
    public BailiffDistrictCodeV10CT createBailiffDistrictCodeV10CT() {
        return new BailiffDistrictCodeV10CT();
    }

    /**
     * Create an instance of {@link SpecialArrangementV10CT }
     * 
     */
    public SpecialArrangementV10CT createSpecialArrangementV10CT() {
        return new SpecialArrangementV10CT();
    }

    /**
     * Create an instance of {@link PartyEnglishAliasNameV10CT }
     * 
     */
    public PartyEnglishAliasNameV10CT createPartyEnglishAliasNameV10CT() {
        return new PartyEnglishAliasNameV10CT();
    }

    /**
     * Create an instance of {@link PartyChineseAliasNameV10CT }
     * 
     */
    public PartyChineseAliasNameV10CT createPartyChineseAliasNameV10CT() {
        return new PartyChineseAliasNameV10CT();
    }

    /**
     * Create an instance of {@link InformantV10CT }
     * 
     */
    public InformantV10CT createInformantV10CT() {
        return new InformantV10CT();
    }

    /**
     * Create an instance of {@link InformantV11CT }
     * 
     */
    public InformantV11CT createInformantV11CT() {
        return new InformantV11CT();
    }

    /**
     * Create an instance of {@link InformantV12CT }
     * 
     */
    public InformantV12CT createInformantV12CT() {
        return new InformantV12CT();
    }

    /**
     * Create an instance of {@link WitnessV10CT }
     * 
     */
    public WitnessV10CT createWitnessV10CT() {
        return new WitnessV10CT();
    }

    /**
     * Create an instance of {@link WitnessV11CT }
     * 
     */
    public WitnessV11CT createWitnessV11CT() {
        return new WitnessV11CT();
    }

    /**
     * Create an instance of {@link WitnessV12CT }
     * 
     */
    public WitnessV12CT createWitnessV12CT() {
        return new WitnessV12CT();
    }

    /**
     * Create an instance of {@link ItemToBeBroughtV10CT }
     * 
     */
    public ItemToBeBroughtV10CT createItemToBeBroughtV10CT() {
        return new ItemToBeBroughtV10CT();
    }

    /**
     * Create an instance of {@link SuretyV10CT }
     * 
     */
    public SuretyV10CT createSuretyV10CT() {
        return new SuretyV10CT();
    }

    /**
     * Create an instance of {@link SODKeyV10CT }
     * 
     */
    public SODKeyV10CT createSODKeyV10CT() {
        return new SODKeyV10CT();
    }

    /**
     * Create an instance of {@link SODKeyV11CT }
     * 
     */
    public SODKeyV11CT createSODKeyV11CT() {
        return new SODKeyV11CT();
    }

    /**
     * Create an instance of {@link ChapterV10CT }
     * 
     */
    public ChapterV10CT createChapterV10CT() {
        return new ChapterV10CT();
    }

    /**
     * Create an instance of {@link ChapterV11CT }
     * 
     */
    public ChapterV11CT createChapterV11CT() {
        return new ChapterV11CT();
    }

    /**
     * Create an instance of {@link SubLegislativeV10CT }
     * 
     */
    public SubLegislativeV10CT createSubLegislativeV10CT() {
        return new SubLegislativeV10CT();
    }

    /**
     * Create an instance of {@link SubLegislativeV11CT }
     * 
     */
    public SubLegislativeV11CT createSubLegislativeV11CT() {
        return new SubLegislativeV11CT();
    }

    /**
     * Create an instance of {@link SectionV10CT }
     * 
     */
    public SectionV10CT createSectionV10CT() {
        return new SectionV10CT();
    }

    /**
     * Create an instance of {@link SectionV11CT }
     * 
     */
    public SectionV11CT createSectionV11CT() {
        return new SectionV11CT();
    }

    /**
     * Create an instance of {@link SubSectionV10CT }
     * 
     */
    public SubSectionV10CT createSubSectionV10CT() {
        return new SubSectionV10CT();
    }

    /**
     * Create an instance of {@link SubSectionV11CT }
     * 
     */
    public SubSectionV11CT createSubSectionV11CT() {
        return new SubSectionV11CT();
    }

    /**
     * Create an instance of {@link ParagraphV10CT }
     * 
     */
    public ParagraphV10CT createParagraphV10CT() {
        return new ParagraphV10CT();
    }

    /**
     * Create an instance of {@link ParagraphV11CT }
     * 
     */
    public ParagraphV11CT createParagraphV11CT() {
        return new ParagraphV11CT();
    }

    /**
     * Create an instance of {@link SubParagraphV10CT }
     * 
     */
    public SubParagraphV10CT createSubParagraphV10CT() {
        return new SubParagraphV10CT();
    }

    /**
     * Create an instance of {@link SubParagraphV11CT }
     * 
     */
    public SubParagraphV11CT createSubParagraphV11CT() {
        return new SubParagraphV11CT();
    }

    /**
     * Create an instance of {@link SupplementCodeV10CT }
     * 
     */
    public SupplementCodeV10CT createSupplementCodeV10CT() {
        return new SupplementCodeV10CT();
    }

    /**
     * Create an instance of {@link SupplementCodeV11CT }
     * 
     */
    public SupplementCodeV11CT createSupplementCodeV11CT() {
        return new SupplementCodeV11CT();
    }

    /**
     * Create an instance of {@link VersionNumberV10CT }
     * 
     */
    public VersionNumberV10CT createVersionNumberV10CT() {
        return new VersionNumberV10CT();
    }

    /**
     * Create an instance of {@link VersionNumberV11CT }
     * 
     */
    public VersionNumberV11CT createVersionNumberV11CT() {
        return new VersionNumberV11CT();
    }

    /**
     * Create an instance of {@link CSODV10CT }
     * 
     */
    public CSODV10CT createCSODV10CT() {
        return new CSODV10CT();
    }

    /**
     * Create an instance of {@link CSODV11CT }
     * 
     */
    public CSODV11CT createCSODV11CT() {
        return new CSODV11CT();
    }

    /**
     * Create an instance of {@link CSODV12CT }
     * 
     */
    public CSODV12CT createCSODV12CT() {
        return new CSODV12CT();
    }

    /**
     * Create an instance of {@link CSODV13CT }
     * 
     */
    public CSODV13CT createCSODV13CT() {
        return new CSODV13CT();
    }

    /**
     * Create an instance of {@link StatusV10CT }
     * 
     */
    public StatusV10CT createStatusV10CT() {
        return new StatusV10CT();
    }

    /**
     * Create an instance of {@link ShortDescriptionV10CT }
     * 
     */
    public ShortDescriptionV10CT createShortDescriptionV10CT() {
        return new ShortDescriptionV10CT();
    }

    /**
     * Create an instance of {@link ShortDescriptionChineseV10CT }
     * 
     */
    public ShortDescriptionChineseV10CT createShortDescriptionChineseV10CT() {
        return new ShortDescriptionChineseV10CT();
    }

    /**
     * Create an instance of {@link ShortDescriptionChineseV11CT }
     * 
     */
    public ShortDescriptionChineseV11CT createShortDescriptionChineseV11CT() {
        return new ShortDescriptionChineseV11CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyFineCodeV10CT }
     * 
     */
    public FixedPenaltyFineCodeV10CT createFixedPenaltyFineCodeV10CT() {
        return new FixedPenaltyFineCodeV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyCostsCodeV10CT }
     * 
     */
    public FixedPenaltyCostsCodeV10CT createFixedPenaltyCostsCodeV10CT() {
        return new FixedPenaltyCostsCodeV10CT();
    }

    /**
     * Create an instance of {@link TimeBarOffenceV10CT }
     * 
     */
    public TimeBarOffenceV10CT createTimeBarOffenceV10CT() {
        return new TimeBarOffenceV10CT();
    }

    /**
     * Create an instance of {@link TimeBarDiscoverV10CT }
     * 
     */
    public TimeBarDiscoverV10CT createTimeBarDiscoverV10CT() {
        return new TimeBarDiscoverV10CT();
    }

    /**
     * Create an instance of {@link FieldIndicatorV10CT }
     * 
     */
    public FieldIndicatorV10CT createFieldIndicatorV10CT() {
        return new FieldIndicatorV10CT();
    }

    /**
     * Create an instance of {@link OffenceDescriptionV10CT }
     * 
     */
    public OffenceDescriptionV10CT createOffenceDescriptionV10CT() {
        return new OffenceDescriptionV10CT();
    }

    /**
     * Create an instance of {@link OffenceDescriptionV11CT }
     * 
     */
    public OffenceDescriptionV11CT createOffenceDescriptionV11CT() {
        return new OffenceDescriptionV11CT();
    }

    /**
     * Create an instance of {@link OffenceDescriptionChineseV10CT }
     * 
     */
    public OffenceDescriptionChineseV10CT createOffenceDescriptionChineseV10CT() {
        return new OffenceDescriptionChineseV10CT();
    }

    /**
     * Create an instance of {@link OffenceDescriptionChineseV11CT }
     * 
     */
    public OffenceDescriptionChineseV11CT createOffenceDescriptionChineseV11CT() {
        return new OffenceDescriptionChineseV11CT();
    }

    /**
     * Create an instance of {@link OffenceDescriptionChineseV12CT }
     * 
     */
    public OffenceDescriptionChineseV12CT createOffenceDescriptionChineseV12CT() {
        return new OffenceDescriptionChineseV12CT();
    }

    /**
     * Create an instance of {@link LawV10CT }
     * 
     */
    public LawV10CT createLawV10CT() {
        return new LawV10CT();
    }

    /**
     * Create an instance of {@link LawChineseV10CT }
     * 
     */
    public LawChineseV10CT createLawChineseV10CT() {
        return new LawChineseV10CT();
    }

    /**
     * Create an instance of {@link LawChineseV11CT }
     * 
     */
    public LawChineseV11CT createLawChineseV11CT() {
        return new LawChineseV11CT();
    }

    /**
     * Create an instance of {@link HearingWeightV10CT }
     * 
     */
    public HearingWeightV10CT createHearingWeightV10CT() {
        return new HearingWeightV10CT();
    }

    /**
     * Create an instance of {@link PenaltyWeightV10CT }
     * 
     */
    public PenaltyWeightV10CT createPenaltyWeightV10CT() {
        return new PenaltyWeightV10CT();
    }

    /**
     * Create an instance of {@link CSODVarListV10CT }
     * 
     */
    public CSODVarListV10CT createCSODVarListV10CT() {
        return new CSODVarListV10CT();
    }

    /**
     * Create an instance of {@link CSODVarListV11CT }
     * 
     */
    public CSODVarListV11CT createCSODVarListV11CT() {
        return new CSODVarListV11CT();
    }

    /**
     * Create an instance of {@link CSODVarDetailV10CT }
     * 
     */
    public CSODVarDetailV10CT createCSODVarDetailV10CT() {
        return new CSODVarDetailV10CT();
    }

    /**
     * Create an instance of {@link CSODVarDetailV11CT }
     * 
     */
    public CSODVarDetailV11CT createCSODVarDetailV11CT() {
        return new CSODVarDetailV11CT();
    }

    /**
     * Create an instance of {@link VariableNumberV10CT }
     * 
     */
    public VariableNumberV10CT createVariableNumberV10CT() {
        return new VariableNumberV10CT();
    }

    /**
     * Create an instance of {@link VariableTypeV10CT }
     * 
     */
    public VariableTypeV10CT createVariableTypeV10CT() {
        return new VariableTypeV10CT();
    }

    /**
     * Create an instance of {@link VariableDescriptionV10CT }
     * 
     */
    public VariableDescriptionV10CT createVariableDescriptionV10CT() {
        return new VariableDescriptionV10CT();
    }

    /**
     * Create an instance of {@link VariableDescriptionChineseV10CT }
     * 
     */
    public VariableDescriptionChineseV10CT createVariableDescriptionChineseV10CT() {
        return new VariableDescriptionChineseV10CT();
    }

    /**
     * Create an instance of {@link VariableDescriptionChineseV11CT }
     * 
     */
    public VariableDescriptionChineseV11CT createVariableDescriptionChineseV11CT() {
        return new VariableDescriptionChineseV11CT();
    }

    /**
     * Create an instance of {@link CaseSODV10CT }
     * 
     */
    public CaseSODV10CT createCaseSODV10CT() {
        return new CaseSODV10CT();
    }

    /**
     * Create an instance of {@link CaseSODV11CT }
     * 
     */
    public CaseSODV11CT createCaseSODV11CT() {
        return new CaseSODV11CT();
    }

    /**
     * Create an instance of {@link CaseSODV12CT }
     * 
     */
    public CaseSODV12CT createCaseSODV12CT() {
        return new CaseSODV12CT();
    }

    /**
     * Create an instance of {@link OffenceDescriptionV12CT }
     * 
     */
    public OffenceDescriptionV12CT createOffenceDescriptionV12CT() {
        return new OffenceDescriptionV12CT();
    }

    /**
     * Create an instance of {@link OffenceDescriptionChineseV13CT }
     * 
     */
    public OffenceDescriptionChineseV13CT createOffenceDescriptionChineseV13CT() {
        return new OffenceDescriptionChineseV13CT();
    }

    /**
     * Create an instance of {@link ContraryToLawV10CT }
     * 
     */
    public ContraryToLawV10CT createContraryToLawV10CT() {
        return new ContraryToLawV10CT();
    }

    /**
     * Create an instance of {@link ContraryToLawChineseV10CT }
     * 
     */
    public ContraryToLawChineseV10CT createContraryToLawChineseV10CT() {
        return new ContraryToLawChineseV10CT();
    }

    /**
     * Create an instance of {@link ChargeParticularV10CT }
     * 
     */
    public ChargeParticularV10CT createChargeParticularV10CT() {
        return new ChargeParticularV10CT();
    }

    /**
     * Create an instance of {@link ChargeParticularChineseV10CT }
     * 
     */
    public ChargeParticularChineseV10CT createChargeParticularChineseV10CT() {
        return new ChargeParticularChineseV10CT();
    }

    /**
     * Create an instance of {@link CaseOffenceV10CT }
     * 
     */
    public CaseOffenceV10CT createCaseOffenceV10CT() {
        return new CaseOffenceV10CT();
    }

    /**
     * Create an instance of {@link CaseOffenceV11CT }
     * 
     */
    public CaseOffenceV11CT createCaseOffenceV11CT() {
        return new CaseOffenceV11CT();
    }

    /**
     * Create an instance of {@link DefendantHearingV10CT }
     * 
     */
    public DefendantHearingV10CT createDefendantHearingV10CT() {
        return new DefendantHearingV10CT();
    }

    /**
     * Create an instance of {@link HearingOutcomeV10CT }
     * 
     */
    public HearingOutcomeV10CT createHearingOutcomeV10CT() {
        return new HearingOutcomeV10CT();
    }

    /**
     * Create an instance of {@link OrderV10CT }
     * 
     */
    public OrderV10CT createOrderV10CT() {
        return new OrderV10CT();
    }

    /**
     * Create an instance of {@link OrderV11CT }
     * 
     */
    public OrderV11CT createOrderV11CT() {
        return new OrderV11CT();
    }

    /**
     * Create an instance of {@link OrderV12CT }
     * 
     */
    public OrderV12CT createOrderV12CT() {
        return new OrderV12CT();
    }

    /**
     * Create an instance of {@link OrderV13CT }
     * 
     */
    public OrderV13CT createOrderV13CT() {
        return new OrderV13CT();
    }

    /**
     * Create an instance of {@link OrderV14CT }
     * 
     */
    public OrderV14CT createOrderV14CT() {
        return new OrderV14CT();
    }

    /**
     * Create an instance of {@link DICTypeV10CT }
     * 
     */
    public DICTypeV10CT createDICTypeV10CT() {
        return new DICTypeV10CT();
    }

    /**
     * Create an instance of {@link DICTypeV11CT }
     * 
     */
    public DICTypeV11CT createDICTypeV11CT() {
        return new DICTypeV11CT();
    }

    /**
     * Create an instance of {@link DqrEntitlementIndV10CT }
     * 
     */
    public DqrEntitlementIndV10CT createDqrEntitlementIndV10CT() {
        return new DqrEntitlementIndV10CT();
    }

    /**
     * Create an instance of {@link DqrEntitlementListV10CT }
     * 
     */
    public DqrEntitlementListV10CT createDqrEntitlementListV10CT() {
        return new DqrEntitlementListV10CT();
    }

    /**
     * Create an instance of {@link LinkSerialNumberV11CT }
     * 
     */
    public LinkSerialNumberV11CT createLinkSerialNumberV11CT() {
        return new LinkSerialNumberV11CT();
    }

    /**
     * Create an instance of {@link OrderInternalNumberV10CT }
     * 
     */
    public OrderInternalNumberV10CT createOrderInternalNumberV10CT() {
        return new OrderInternalNumberV10CT();
    }

    /**
     * Create an instance of {@link OrderCodeV10CT }
     * 
     */
    public OrderCodeV10CT createOrderCodeV10CT() {
        return new OrderCodeV10CT();
    }

    /**
     * Create an instance of {@link YearV10CT }
     * 
     */
    public YearV10CT createYearV10CT() {
        return new YearV10CT();
    }

    /**
     * Create an instance of {@link MonthV10CT }
     * 
     */
    public MonthV10CT createMonthV10CT() {
        return new MonthV10CT();
    }

    /**
     * Create an instance of {@link WeekV10CT }
     * 
     */
    public WeekV10CT createWeekV10CT() {
        return new WeekV10CT();
    }

    /**
     * Create an instance of {@link DayV10CT }
     * 
     */
    public DayV10CT createDayV10CT() {
        return new DayV10CT();
    }

    /**
     * Create an instance of {@link HourV10CT }
     * 
     */
    public HourV10CT createHourV10CT() {
        return new HourV10CT();
    }

    /**
     * Create an instance of {@link CurrencyCodeV10CT }
     * 
     */
    public CurrencyCodeV10CT createCurrencyCodeV10CT() {
        return new CurrencyCodeV10CT();
    }

    /**
     * Create an instance of {@link AmountV10CT }
     * 
     */
    public AmountV10CT createAmountV10CT() {
        return new AmountV10CT();
    }

    /**
     * Create an instance of {@link AppealV10CT }
     * 
     */
    public AppealV10CT createAppealV10CT() {
        return new AppealV10CT();
    }

    /**
     * Create an instance of {@link AppealInternalNumberV10CT }
     * 
     */
    public AppealInternalNumberV10CT createAppealInternalNumberV10CT() {
        return new AppealInternalNumberV10CT();
    }

    /**
     * Create an instance of {@link AppealRegisterNumberV10CT }
     * 
     */
    public AppealRegisterNumberV10CT createAppealRegisterNumberV10CT() {
        return new AppealRegisterNumberV10CT();
    }

    /**
     * Create an instance of {@link AppealAppliedPartyV10CT }
     * 
     */
    public AppealAppliedPartyV10CT createAppealAppliedPartyV10CT() {
        return new AppealAppliedPartyV10CT();
    }

    /**
     * Create an instance of {@link ReviewV10CT }
     * 
     */
    public ReviewV10CT createReviewV10CT() {
        return new ReviewV10CT();
    }

    /**
     * Create an instance of {@link ReviewInternalNumberV10CT }
     * 
     */
    public ReviewInternalNumberV10CT createReviewInternalNumberV10CT() {
        return new ReviewInternalNumberV10CT();
    }

    /**
     * Create an instance of {@link ReviewAppliedPartyV10CT }
     * 
     */
    public ReviewAppliedPartyV10CT createReviewAppliedPartyV10CT() {
        return new ReviewAppliedPartyV10CT();
    }

    /**
     * Create an instance of {@link ErrorMessageV10CT }
     * 
     */
    public ErrorMessageV10CT createErrorMessageV10CT() {
        return new ErrorMessageV10CT();
    }

    /**
     * Create an instance of {@link ErrorDetailsV10CT }
     * 
     */
    public ErrorDetailsV10CT createErrorDetailsV10CT() {
        return new ErrorDetailsV10CT();
    }

    /**
     * Create an instance of {@link DurationV10CT }
     * 
     */
    public DurationV10CT createDurationV10CT() {
        return new DurationV10CT();
    }

    /**
     * Create an instance of {@link MinuteV10CT }
     * 
     */
    public MinuteV10CT createMinuteV10CT() {
        return new MinuteV10CT();
    }

    /**
     * Create an instance of {@link MinuteV11CT }
     * 
     */
    public MinuteV11CT createMinuteV11CT() {
        return new MinuteV11CT();
    }

    /**
     * Create an instance of {@link SecondV10CT }
     * 
     */
    public SecondV10CT createSecondV10CT() {
        return new SecondV10CT();
    }

    /**
     * Create an instance of {@link VehicleRegistrationMarkV10CT }
     * 
     */
    public VehicleRegistrationMarkV10CT createVehicleRegistrationMarkV10CT() {
        return new VehicleRegistrationMarkV10CT();
    }

    /**
     * Create an instance of {@link VehicleRegistrationMarkDigitV10CT }
     * 
     */
    public VehicleRegistrationMarkDigitV10CT createVehicleRegistrationMarkDigitV10CT() {
        return new VehicleRegistrationMarkDigitV10CT();
    }

    /**
     * Create an instance of {@link PaymentOrderV10CT }
     * 
     */
    public PaymentOrderV10CT createPaymentOrderV10CT() {
        return new PaymentOrderV10CT();
    }

    /**
     * Create an instance of {@link PaymentTypeV10CT }
     * 
     */
    public PaymentTypeV10CT createPaymentTypeV10CT() {
        return new PaymentTypeV10CT();
    }

    /**
     * Create an instance of {@link PaymentParameterV10CT }
     * 
     */
    public PaymentParameterV10CT createPaymentParameterV10CT() {
        return new PaymentParameterV10CT();
    }

    /**
     * Create an instance of {@link InterfaceFileHeaderV10CT }
     * 
     */
    public InterfaceFileHeaderV10CT createInterfaceFileHeaderV10CT() {
        return new InterfaceFileHeaderV10CT();
    }

    /**
     * Create an instance of {@link InterfaceFileHeaderV11CT }
     * 
     */
    public InterfaceFileHeaderV11CT createInterfaceFileHeaderV11CT() {
        return new InterfaceFileHeaderV11CT();
    }

    /**
     * Create an instance of {@link InterfaceFileHeaderV12CT }
     * 
     */
    public InterfaceFileHeaderV12CT createInterfaceFileHeaderV12CT() {
        return new InterfaceFileHeaderV12CT();
    }

    /**
     * Create an instance of {@link PrefixV10CT }
     * 
     */
    public PrefixV10CT createPrefixV10CT() {
        return new PrefixV10CT();
    }

    /**
     * Create an instance of {@link PrefixV11CT }
     * 
     */
    public PrefixV11CT createPrefixV11CT() {
        return new PrefixV11CT();
    }

    /**
     * Create an instance of {@link PrefixV12CT }
     * 
     */
    public PrefixV12CT createPrefixV12CT() {
        return new PrefixV12CT();
    }

    /**
     * Create an instance of {@link PrefixV13CT }
     * 
     */
    public PrefixV13CT createPrefixV13CT() {
        return new PrefixV13CT();
    }

    /**
     * Create an instance of {@link BatchSerialNumberV10CT }
     * 
     */
    public BatchSerialNumberV10CT createBatchSerialNumberV10CT() {
        return new BatchSerialNumberV10CT();
    }

    /**
     * Create an instance of {@link XMLRecordCountV10CT }
     * 
     */
    public XMLRecordCountV10CT createXMLRecordCountV10CT() {
        return new XMLRecordCountV10CT();
    }

    /**
     * Create an instance of {@link OffenceDetailsV10CT }
     * 
     */
    public OffenceDetailsV10CT createOffenceDetailsV10CT() {
        return new OffenceDetailsV10CT();
    }

    /**
     * Create an instance of {@link OffenceDetailsV11CT }
     * 
     */
    public OffenceDetailsV11CT createOffenceDetailsV11CT() {
        return new OffenceDetailsV11CT();
    }

    /**
     * Create an instance of {@link OffenceDateTimeV10CT }
     * 
     */
    public OffenceDateTimeV10CT createOffenceDateTimeV10CT() {
        return new OffenceDateTimeV10CT();
    }

    /**
     * Create an instance of {@link OffenceDateFormatV10CT }
     * 
     */
    public OffenceDateFormatV10CT createOffenceDateFormatV10CT() {
        return new OffenceDateFormatV10CT();
    }

    /**
     * Create an instance of {@link TimeBarMethodV10CT }
     * 
     */
    public TimeBarMethodV10CT createTimeBarMethodV10CT() {
        return new TimeBarMethodV10CT();
    }

    /**
     * Create an instance of {@link InterfaceOffenceCodeV10CT }
     * 
     */
    public InterfaceOffenceCodeV10CT createInterfaceOffenceCodeV10CT() {
        return new InterfaceOffenceCodeV10CT();
    }

    /**
     * Create an instance of {@link OffenceDescFormatV10CT }
     * 
     */
    public OffenceDescFormatV10CT createOffenceDescFormatV10CT() {
        return new OffenceDescFormatV10CT();
    }

    /**
     * Create an instance of {@link AuthorizeUserIDV10CT }
     * 
     */
    public AuthorizeUserIDV10CT createAuthorizeUserIDV10CT() {
        return new AuthorizeUserIDV10CT();
    }

    /**
     * Create an instance of {@link InputUserIDV10CT }
     * 
     */
    public InputUserIDV10CT createInputUserIDV10CT() {
        return new InputUserIDV10CT();
    }

    /**
     * Create an instance of {@link InterfaceIDV10CT }
     * 
     */
    public InterfaceIDV10CT createInterfaceIDV10CT() {
        return new InterfaceIDV10CT();
    }

    /**
     * Create an instance of {@link ProcessStatusV10CT }
     * 
     */
    public ProcessStatusV10CT createProcessStatusV10CT() {
        return new ProcessStatusV10CT();
    }

    /**
     * Create an instance of {@link HostReturnCodeV10CT }
     * 
     */
    public HostReturnCodeV10CT createHostReturnCodeV10CT() {
        return new HostReturnCodeV10CT();
    }

    /**
     * Create an instance of {@link OffenceDescV10CT }
     * 
     */
    public OffenceDescV10CT createOffenceDescV10CT() {
        return new OffenceDescV10CT();
    }

    /**
     * Create an instance of {@link OffenceDescV11CT }
     * 
     */
    public OffenceDescV11CT createOffenceDescV11CT() {
        return new OffenceDescV11CT();
    }

    /**
     * Create an instance of {@link OffenceDescV12CT }
     * 
     */
    public OffenceDescV12CT createOffenceDescV12CT() {
        return new OffenceDescV12CT();
    }

    /**
     * Create an instance of {@link OffenceVariableV10CT }
     * 
     */
    public OffenceVariableV10CT createOffenceVariableV10CT() {
        return new OffenceVariableV10CT();
    }

    /**
     * Create an instance of {@link OffenceVarValueV10CT }
     * 
     */
    public OffenceVarValueV10CT createOffenceVarValueV10CT() {
        return new OffenceVarValueV10CT();
    }

    /**
     * Create an instance of {@link OffenceVarValueChineseV10CT }
     * 
     */
    public OffenceVarValueChineseV10CT createOffenceVarValueChineseV10CT() {
        return new OffenceVarValueChineseV10CT();
    }

    /**
     * Create an instance of {@link RecordStatusV10CT }
     * 
     */
    public RecordStatusV10CT createRecordStatusV10CT() {
        return new RecordStatusV10CT();
    }

    /**
     * Create an instance of {@link RecordStatusV11CT }
     * 
     */
    public RecordStatusV11CT createRecordStatusV11CT() {
        return new RecordStatusV11CT();
    }

    /**
     * Create an instance of {@link RecordStatusV12CT }
     * 
     */
    public RecordStatusV12CT createRecordStatusV12CT() {
        return new RecordStatusV12CT();
    }

    /**
     * Create an instance of {@link RecordSequenceNumberV10CT }
     * 
     */
    public RecordSequenceNumberV10CT createRecordSequenceNumberV10CT() {
        return new RecordSequenceNumberV10CT();
    }

    /**
     * Create an instance of {@link ApplicationStatusV10CT }
     * 
     */
    public ApplicationStatusV10CT createApplicationStatusV10CT() {
        return new ApplicationStatusV10CT();
    }

    /**
     * Create an instance of {@link RemarkLineV10CT }
     * 
     */
    public RemarkLineV10CT createRemarkLineV10CT() {
        return new RemarkLineV10CT();
    }

    /**
     * Create an instance of {@link PartyTypeV10CT }
     * 
     */
    public PartyTypeV10CT createPartyTypeV10CT() {
        return new PartyTypeV10CT();
    }

    /**
     * Create an instance of {@link PartyNoV10CT }
     * 
     */
    public PartyNoV10CT createPartyNoV10CT() {
        return new PartyNoV10CT();
    }

    /**
     * Create an instance of {@link DemandNoteNumberV10CT }
     * 
     */
    public DemandNoteNumberV10CT createDemandNoteNumberV10CT() {
        return new DemandNoteNumberV10CT();
    }

    /**
     * Create an instance of {@link DemandNoteNumberV11CT }
     * 
     */
    public DemandNoteNumberV11CT createDemandNoteNumberV11CT() {
        return new DemandNoteNumberV11CT();
    }

    /**
     * Create an instance of {@link CaseRowSequenceNumberV10CT }
     * 
     */
    public CaseRowSequenceNumberV10CT createCaseRowSequenceNumberV10CT() {
        return new CaseRowSequenceNumberV10CT();
    }

    /**
     * Create an instance of {@link AmountV11CT }
     * 
     */
    public AmountV11CT createAmountV11CT() {
        return new AmountV11CT();
    }

    /**
     * Create an instance of {@link AdditionalSectionV10CT }
     * 
     */
    public AdditionalSectionV10CT createAdditionalSectionV10CT() {
        return new AdditionalSectionV10CT();
    }

    /**
     * Create an instance of {@link PreferredWarrantTypeV10CT }
     * 
     */
    public PreferredWarrantTypeV10CT createPreferredWarrantTypeV10CT() {
        return new PreferredWarrantTypeV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyApplicationNatureV10CT }
     * 
     */
    public FixedPenaltyApplicationNatureV10CT createFixedPenaltyApplicationNatureV10CT() {
        return new FixedPenaltyApplicationNatureV10CT();
    }

    /**
     * Create an instance of {@link RecordTypeV10CT }
     * 
     */
    public RecordTypeV10CT createRecordTypeV10CT() {
        return new RecordTypeV10CT();
    }

    /**
     * Create an instance of {@link PleaTypeV10CT }
     * 
     */
    public PleaTypeV10CT createPleaTypeV10CT() {
        return new PleaTypeV10CT();
    }

    /**
     * Create an instance of {@link CommonAmendmentV10CT }
     * 
     */
    public CommonAmendmentV10CT createCommonAmendmentV10CT() {
        return new CommonAmendmentV10CT();
    }

    /**
     * Create an instance of {@link AmendmentActionV10CT }
     * 
     */
    public AmendmentActionV10CT createAmendmentActionV10CT() {
        return new AmendmentActionV10CT();
    }

    /**
     * Create an instance of {@link AmendmentDataNameV10CT }
     * 
     */
    public AmendmentDataNameV10CT createAmendmentDataNameV10CT() {
        return new AmendmentDataNameV10CT();
    }

    /**
     * Create an instance of {@link AmendmentDataValueV10CT }
     * 
     */
    public AmendmentDataValueV10CT createAmendmentDataValueV10CT() {
        return new AmendmentDataValueV10CT();
    }

    /**
     * Create an instance of {@link OffenceAmendmentV10CT }
     * 
     */
    public OffenceAmendmentV10CT createOffenceAmendmentV10CT() {
        return new OffenceAmendmentV10CT();
    }

    /**
     * Create an instance of {@link DefendantAmendmentV10CT }
     * 
     */
    public DefendantAmendmentV10CT createDefendantAmendmentV10CT() {
        return new DefendantAmendmentV10CT();
    }

    /**
     * Create an instance of {@link WitnessAmendmentV10CT }
     * 
     */
    public WitnessAmendmentV10CT createWitnessAmendmentV10CT() {
        return new WitnessAmendmentV10CT();
    }

    /**
     * Create an instance of {@link SuretyAmendmentV10CT }
     * 
     */
    public SuretyAmendmentV10CT createSuretyAmendmentV10CT() {
        return new SuretyAmendmentV10CT();
    }

    /**
     * Create an instance of {@link BailRemandAmendmentV10CT }
     * 
     */
    public BailRemandAmendmentV10CT createBailRemandAmendmentV10CT() {
        return new BailRemandAmendmentV10CT();
    }

    /**
     * Create an instance of {@link ChargeTypeV10CT }
     * 
     */
    public ChargeTypeV10CT createChargeTypeV10CT() {
        return new ChargeTypeV10CT();
    }

    /**
     * Create an instance of {@link OffenceDateTypeV10CT }
     * 
     */
    public OffenceDateTypeV10CT createOffenceDateTypeV10CT() {
        return new OffenceDateTypeV10CT();
    }

    /**
     * Create an instance of {@link OffenceDateFreetextV10CT }
     * 
     */
    public OffenceDateFreetextV10CT createOffenceDateFreetextV10CT() {
        return new OffenceDateFreetextV10CT();
    }

    /**
     * Create an instance of {@link BailRemandV10CT }
     * 
     */
    public BailRemandV10CT createBailRemandV10CT() {
        return new BailRemandV10CT();
    }

    /**
     * Create an instance of {@link PeriodTypeV10CT }
     * 
     */
    public PeriodTypeV10CT createPeriodTypeV10CT() {
        return new PeriodTypeV10CT();
    }

    /**
     * Create an instance of {@link BailTypeV10CT }
     * 
     */
    public BailTypeV10CT createBailTypeV10CT() {
        return new BailTypeV10CT();
    }

    /**
     * Create an instance of {@link RelationshipCodeV10CT }
     * 
     */
    public RelationshipCodeV10CT createRelationshipCodeV10CT() {
        return new RelationshipCodeV10CT();
    }

    /**
     * Create an instance of {@link RelationshipTextV10CT }
     * 
     */
    public RelationshipTextV10CT createRelationshipTextV10CT() {
        return new RelationshipTextV10CT();
    }

    /**
     * Create an instance of {@link BailConditionV10CT }
     * 
     */
    public BailConditionV10CT createBailConditionV10CT() {
        return new BailConditionV10CT();
    }

    /**
     * Create an instance of {@link ReportFrequencyV10CT }
     * 
     */
    public ReportFrequencyV10CT createReportFrequencyV10CT() {
        return new ReportFrequencyV10CT();
    }

    /**
     * Create an instance of {@link BailRegisterNumberV10CT }
     * 
     */
    public BailRegisterNumberV10CT createBailRegisterNumberV10CT() {
        return new BailRegisterNumberV10CT();
    }

    /**
     * Create an instance of {@link BailBookSerialNumberV10CT }
     * 
     */
    public BailBookSerialNumberV10CT createBailBookSerialNumberV10CT() {
        return new BailBookSerialNumberV10CT();
    }

    /**
     * Create an instance of {@link OrderByChargeV10CT }
     * 
     */
    public OrderByChargeV10CT createOrderByChargeV10CT() {
        return new OrderByChargeV10CT();
    }

    /**
     * Create an instance of {@link HearingResultDescriptionV10CT }
     * 
     */
    public HearingResultDescriptionV10CT createHearingResultDescriptionV10CT() {
        return new HearingResultDescriptionV10CT();
    }

    /**
     * Create an instance of {@link OrderByDefendantV10CT }
     * 
     */
    public OrderByDefendantV10CT createOrderByDefendantV10CT() {
        return new OrderByDefendantV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseV10CT }
     * 
     */
    public ChargeCaseV10CT createChargeCaseV10CT() {
        return new ChargeCaseV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseOffenceV10CT }
     * 
     */
    public ChargeCaseOffenceV10CT createChargeCaseOffenceV10CT() {
        return new ChargeCaseOffenceV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseOffenceDateV10CT }
     * 
     */
    public ChargeCaseOffenceDateV10CT createChargeCaseOffenceDateV10CT() {
        return new ChargeCaseOffenceDateV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseDefendantV10CT }
     * 
     */
    public ChargeCaseDefendantV10CT createChargeCaseDefendantV10CT() {
        return new ChargeCaseDefendantV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseAllocationRemarkV10CT }
     * 
     */
    public ChargeCaseAllocationRemarkV10CT createChargeCaseAllocationRemarkV10CT() {
        return new ChargeCaseAllocationRemarkV10CT();
    }

    /**
     * Create an instance of {@link ChargeCaseAmendmentV10CT }
     * 
     */
    public ChargeCaseAmendmentV10CT createChargeCaseAmendmentV10CT() {
        return new ChargeCaseAmendmentV10CT();
    }

    /**
     * Create an instance of {@link AmendmentReferenceNumberV10CT }
     * 
     */
    public AmendmentReferenceNumberV10CT createAmendmentReferenceNumberV10CT() {
        return new AmendmentReferenceNumberV10CT();
    }

    /**
     * Create an instance of {@link AmendmentApplicationRemarkV10CT }
     * 
     */
    public AmendmentApplicationRemarkV10CT createAmendmentApplicationRemarkV10CT() {
        return new AmendmentApplicationRemarkV10CT();
    }

    /**
     * Create an instance of {@link CaseDocumentV10CT }
     * 
     */
    public CaseDocumentV10CT createCaseDocumentV10CT() {
        return new CaseDocumentV10CT();
    }

    /**
     * Create an instance of {@link DocumentReferenceNumberV10CT }
     * 
     */
    public DocumentReferenceNumberV10CT createDocumentReferenceNumberV10CT() {
        return new DocumentReferenceNumberV10CT();
    }

    /**
     * Create an instance of {@link DocumentTitleV10CT }
     * 
     */
    public DocumentTitleV10CT createDocumentTitleV10CT() {
        return new DocumentTitleV10CT();
    }

    /**
     * Create an instance of {@link DocumentTypeV10CT }
     * 
     */
    public DocumentTypeV10CT createDocumentTypeV10CT() {
        return new DocumentTypeV10CT();
    }

    /**
     * Create an instance of {@link DocumentFormatV10CT }
     * 
     */
    public DocumentFormatV10CT createDocumentFormatV10CT() {
        return new DocumentFormatV10CT();
    }

    /**
     * Create an instance of {@link SubmitPartyV10CT }
     * 
     */
    public SubmitPartyV10CT createSubmitPartyV10CT() {
        return new SubmitPartyV10CT();
    }

    /**
     * Create an instance of {@link SubmitterNameV10CT }
     * 
     */
    public SubmitterNameV10CT createSubmitterNameV10CT() {
        return new SubmitterNameV10CT();
    }

    /**
     * Create an instance of {@link DocumentStatusV10CT }
     * 
     */
    public DocumentStatusV10CT createDocumentStatusV10CT() {
        return new DocumentStatusV10CT();
    }

    /**
     * Create an instance of {@link HearingResultV10CT }
     * 
     */
    public HearingResultV10CT createHearingResultV10CT() {
        return new HearingResultV10CT();
    }

    /**
     * Create an instance of {@link HearingResultV20CT }
     * 
     */
    public HearingResultV20CT createHearingResultV20CT() {
        return new HearingResultV20CT();
    }

    /**
     * Create an instance of {@link NoticeHearingResultV10CT }
     * 
     */
    public NoticeHearingResultV10CT createNoticeHearingResultV10CT() {
        return new NoticeHearingResultV10CT();
    }

    /**
     * Create an instance of {@link NoticeHearingResultV20CT }
     * 
     */
    public NoticeHearingResultV20CT createNoticeHearingResultV20CT() {
        return new NoticeHearingResultV20CT();
    }

    /**
     * Create an instance of {@link HearingOrderV10CT }
     * 
     */
    public HearingOrderV10CT createHearingOrderV10CT() {
        return new HearingOrderV10CT();
    }

    /**
     * Create an instance of {@link HearingOrderV11CT }
     * 
     */
    public HearingOrderV11CT createHearingOrderV11CT() {
        return new HearingOrderV11CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyNoticeOfOrderCourtResultV10CT }
     * 
     */
    public FixedPenaltyNoticeOfOrderCourtResultV10CT createFixedPenaltyNoticeOfOrderCourtResultV10CT() {
        return new FixedPenaltyNoticeOfOrderCourtResultV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyNoticeOfOrderCourtResultV11CT }
     * 
     */
    public FixedPenaltyNoticeOfOrderCourtResultV11CT createFixedPenaltyNoticeOfOrderCourtResultV11CT() {
        return new FixedPenaltyNoticeOfOrderCourtResultV11CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyNoticeOfOrderCourtResultV20CT }
     * 
     */
    public FixedPenaltyNoticeOfOrderCourtResultV20CT createFixedPenaltyNoticeOfOrderCourtResultV20CT() {
        return new FixedPenaltyNoticeOfOrderCourtResultV20CT();
    }

    /**
     * Create an instance of {@link NoticeOfOrderCourtResultTypeV10CT }
     * 
     */
    public NoticeOfOrderCourtResultTypeV10CT createNoticeOfOrderCourtResultTypeV10CT() {
        return new NoticeOfOrderCourtResultTypeV10CT();
    }

    /**
     * Create an instance of {@link NoticeOfOrderCourtResultCodeV10CT }
     * 
     */
    public NoticeOfOrderCourtResultCodeV10CT createNoticeOfOrderCourtResultCodeV10CT() {
        return new NoticeOfOrderCourtResultCodeV10CT();
    }

    /**
     * Create an instance of {@link NoticeOfOrderCourtResultCodeV101CT }
     * 
     */
    public NoticeOfOrderCourtResultCodeV101CT createNoticeOfOrderCourtResultCodeV101CT() {
        return new NoticeOfOrderCourtResultCodeV101CT();
    }

    /**
     * Create an instance of {@link FixedPenaltySummonsCourtResultV10CT }
     * 
     */
    public FixedPenaltySummonsCourtResultV10CT createFixedPenaltySummonsCourtResultV10CT() {
        return new FixedPenaltySummonsCourtResultV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltySummonsCourtResultV11CT }
     * 
     */
    public FixedPenaltySummonsCourtResultV11CT createFixedPenaltySummonsCourtResultV11CT() {
        return new FixedPenaltySummonsCourtResultV11CT();
    }

    /**
     * Create an instance of {@link FixedPenaltySummonsCourtResultV20CT }
     * 
     */
    public FixedPenaltySummonsCourtResultV20CT createFixedPenaltySummonsCourtResultV20CT() {
        return new FixedPenaltySummonsCourtResultV20CT();
    }

    /**
     * Create an instance of {@link FixedPenaltySummonsCourtResultTypeV10CT }
     * 
     */
    public FixedPenaltySummonsCourtResultTypeV10CT createFixedPenaltySummonsCourtResultTypeV10CT() {
        return new FixedPenaltySummonsCourtResultTypeV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltySummonsCourtResultCodeV10CT }
     * 
     */
    public FixedPenaltySummonsCourtResultCodeV10CT createFixedPenaltySummonsCourtResultCodeV10CT() {
        return new FixedPenaltySummonsCourtResultCodeV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltySummonsCourtResultCodeV101CT }
     * 
     */
    public FixedPenaltySummonsCourtResultCodeV101CT createFixedPenaltySummonsCourtResultCodeV101CT() {
        return new FixedPenaltySummonsCourtResultCodeV101CT();
    }

    /**
     * Create an instance of {@link HearingElapsedTimeV10CT }
     * 
     */
    public HearingElapsedTimeV10CT createHearingElapsedTimeV10CT() {
        return new HearingElapsedTimeV10CT();
    }

    /**
     * Create an instance of {@link NextHearingV10CT }
     * 
     */
    public NextHearingV10CT createNextHearingV10CT() {
        return new NextHearingV10CT();
    }

    /**
     * Create an instance of {@link NextHearingV11CT }
     * 
     */
    public NextHearingV11CT createNextHearingV11CT() {
        return new NextHearingV11CT();
    }

    /**
     * Create an instance of {@link NextHearingV12CT }
     * 
     */
    public NextHearingV12CT createNextHearingV12CT() {
        return new NextHearingV12CT();
    }

    /**
     * Create an instance of {@link WitnessSummonsApplicationV10CT }
     * 
     */
    public WitnessSummonsApplicationV10CT createWitnessSummonsApplicationV10CT() {
        return new WitnessSummonsApplicationV10CT();
    }

    /**
     * Create an instance of {@link WitnessSummonsApplicationV20CT }
     * 
     */
    public WitnessSummonsApplicationV20CT createWitnessSummonsApplicationV20CT() {
        return new WitnessSummonsApplicationV20CT();
    }

    /**
     * Create an instance of {@link WitnessSummonsAllocationV10CT }
     * 
     */
    public WitnessSummonsAllocationV10CT createWitnessSummonsAllocationV10CT() {
        return new WitnessSummonsAllocationV10CT();
    }

    /**
     * Create an instance of {@link WitnessSummonsInternalNumberV10CT }
     * 
     */
    public WitnessSummonsInternalNumberV10CT createWitnessSummonsInternalNumberV10CT() {
        return new WitnessSummonsInternalNumberV10CT();
    }

    /**
     * Create an instance of {@link ApplyPartyV10CT }
     * 
     */
    public ApplyPartyV10CT createApplyPartyV10CT() {
        return new ApplyPartyV10CT();
    }

    /**
     * Create an instance of {@link BailiffDistrictV10CT }
     * 
     */
    public BailiffDistrictV10CT createBailiffDistrictV10CT() {
        return new BailiffDistrictV10CT();
    }

    /**
     * Create an instance of {@link WitnessSummonsAllocationRemarkV10CT }
     * 
     */
    public WitnessSummonsAllocationRemarkV10CT createWitnessSummonsAllocationRemarkV10CT() {
        return new WitnessSummonsAllocationRemarkV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyWitnessSummonsApplicationV10CT }
     * 
     */
    public FixedPenaltyWitnessSummonsApplicationV10CT createFixedPenaltyWitnessSummonsApplicationV10CT() {
        return new FixedPenaltyWitnessSummonsApplicationV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyWitnessSummonsApplicationV11CT }
     * 
     */
    public FixedPenaltyWitnessSummonsApplicationV11CT createFixedPenaltyWitnessSummonsApplicationV11CT() {
        return new FixedPenaltyWitnessSummonsApplicationV11CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyWitnessSummonsApplicationV12CT }
     * 
     */
    public FixedPenaltyWitnessSummonsApplicationV12CT createFixedPenaltyWitnessSummonsApplicationV12CT() {
        return new FixedPenaltyWitnessSummonsApplicationV12CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyWitnessSummonsAllocationV10CT }
     * 
     */
    public FixedPenaltyWitnessSummonsAllocationV10CT createFixedPenaltyWitnessSummonsAllocationV10CT() {
        return new FixedPenaltyWitnessSummonsAllocationV10CT();
    }

    /**
     * Create an instance of {@link FixedPenaltyWitnessSummonsAllocationV11CT }
     * 
     */
    public FixedPenaltyWitnessSummonsAllocationV11CT createFixedPenaltyWitnessSummonsAllocationV11CT() {
        return new FixedPenaltyWitnessSummonsAllocationV11CT();
    }

    /**
     * Create an instance of {@link WritInternalNumberV10CT }
     * 
     */
    public WritInternalNumberV10CT createWritInternalNumberV10CT() {
        return new WritInternalNumberV10CT();
    }

    /**
     * Create an instance of {@link PersonChineseNameDetailsV10CT }
     * 
     */
    public PersonChineseNameDetailsV10CT createPersonChineseNameDetailsV10CT() {
        return new PersonChineseNameDetailsV10CT();
    }

    /**
     * Create an instance of {@link PersonChineseNameNameV10CT }
     * 
     */
    public PersonChineseNameNameV10CT createPersonChineseNameNameV10CT() {
        return new PersonChineseNameNameV10CT();
    }

    /**
     * Create an instance of {@link ChineseCommercialCodeDetailsV10CT }
     * 
     */
    public ChineseCommercialCodeDetailsV10CT createChineseCommercialCodeDetailsV10CT() {
        return new ChineseCommercialCodeDetailsV10CT();
    }

    /**
     * Create an instance of {@link ChineseCommercialCodeFourDigitCodeTextV10CT }
     * 
     */
    public ChineseCommercialCodeFourDigitCodeTextV10CT createChineseCommercialCodeFourDigitCodeTextV10CT() {
        return new ChineseCommercialCodeFourDigitCodeTextV10CT();
    }

    /**
     * Create an instance of {@link ChineseCommercialCodeExtensionNumberTextV10CT }
     * 
     */
    public ChineseCommercialCodeExtensionNumberTextV10CT createChineseCommercialCodeExtensionNumberTextV10CT() {
        return new ChineseCommercialCodeExtensionNumberTextV10CT();
    }

    /**
     * Create an instance of {@link AmountCT }
     * 
     */
    public AmountCT createAmountCT() {
        return new AmountCT();
    }

    /**
     * Create an instance of {@link BinaryObjectCT }
     * 
     */
    public BinaryObjectCT createBinaryObjectCT() {
        return new BinaryObjectCT();
    }

    /**
     * Create an instance of {@link GraphicsCT }
     * 
     */
    public GraphicsCT createGraphicsCT() {
        return new GraphicsCT();
    }

    /**
     * Create an instance of {@link PictureCT }
     * 
     */
    public PictureCT createPictureCT() {
        return new PictureCT();
    }

    /**
     * Create an instance of {@link SoundCT }
     * 
     */
    public SoundCT createSoundCT() {
        return new SoundCT();
    }

    /**
     * Create an instance of {@link VideoCT }
     * 
     */
    public VideoCT createVideoCT() {
        return new VideoCT();
    }

    /**
     * Create an instance of {@link CodeCT }
     * 
     */
    public CodeCT createCodeCT() {
        return new CodeCT();
    }

    /**
     * Create an instance of {@link DateCT }
     * 
     */
    public DateCT createDateCT() {
        return new DateCT();
    }

    /**
     * Create an instance of {@link DateTimeCT }
     * 
     */
    public DateTimeCT createDateTimeCT() {
        return new DateTimeCT();
    }

    /**
     * Create an instance of {@link TimeCT }
     * 
     */
    public TimeCT createTimeCT() {
        return new TimeCT();
    }

    /**
     * Create an instance of {@link IdentifierCT }
     * 
     */
    public IdentifierCT createIdentifierCT() {
        return new IdentifierCT();
    }

    /**
     * Create an instance of {@link IndicatorCT }
     * 
     */
    public IndicatorCT createIndicatorCT() {
        return new IndicatorCT();
    }

    /**
     * Create an instance of {@link BooleanCT }
     * 
     */
    public BooleanCT createBooleanCT() {
        return new BooleanCT();
    }

    /**
     * Create an instance of {@link MeasureCT }
     * 
     */
    public MeasureCT createMeasureCT() {
        return new MeasureCT();
    }

    /**
     * Create an instance of {@link NumericCT }
     * 
     */
    public NumericCT createNumericCT() {
        return new NumericCT();
    }

    /**
     * Create an instance of {@link PercentCT }
     * 
     */
    public PercentCT createPercentCT() {
        return new PercentCT();
    }

    /**
     * Create an instance of {@link RateCT }
     * 
     */
    public RateCT createRateCT() {
        return new RateCT();
    }

    /**
     * Create an instance of {@link ValueCT }
     * 
     */
    public ValueCT createValueCT() {
        return new ValueCT();
    }

    /**
     * Create an instance of {@link QuantityCT }
     * 
     */
    public QuantityCT createQuantityCT() {
        return new QuantityCT();
    }

    /**
     * Create an instance of {@link CountCT }
     * 
     */
    public CountCT createCountCT() {
        return new CountCT();
    }

    /**
     * Create an instance of {@link TextCT }
     * 
     */
    public TextCT createTextCT() {
        return new TextCT();
    }

    /**
     * Create an instance of {@link NameCT }
     * 
     */
    public NameCT createNameCT() {
        return new NameCT();
    }

    /**
     * Create an instance of {@link ElectronicAddressCT }
     * 
     */
    public ElectronicAddressCT createElectronicAddressCT() {
        return new ElectronicAddressCT();
    }

    /**
     * Create an instance of {@link URICT }
     * 
     */
    public URICT createURICT() {
        return new URICT();
    }

    /**
     * Create an instance of {@link PersonEnglishNameDetailsV10CT }
     * 
     */
    public PersonEnglishNameDetailsV10CT createPersonEnglishNameDetailsV10CT() {
        return new PersonEnglishNameDetailsV10CT();
    }

    /**
     * Create an instance of {@link PersonEnglishNameUnstructuredNameV10CT }
     * 
     */
    public PersonEnglishNameUnstructuredNameV10CT createPersonEnglishNameUnstructuredNameV10CT() {
        return new PersonEnglishNameUnstructuredNameV10CT();
    }

    /**
     * Create an instance of {@link PersonEnglishStructuredNameDetailsV10CT }
     * 
     */
    public PersonEnglishStructuredNameDetailsV10CT createPersonEnglishStructuredNameDetailsV10CT() {
        return new PersonEnglishStructuredNameDetailsV10CT();
    }

    /**
     * Create an instance of {@link PersonEnglishStructuredNameSurnameNameV10CT }
     * 
     */
    public PersonEnglishStructuredNameSurnameNameV10CT createPersonEnglishStructuredNameSurnameNameV10CT() {
        return new PersonEnglishStructuredNameSurnameNameV10CT();
    }

    /**
     * Create an instance of {@link PersonEnglishStructuredNameGivenNameV10CT }
     * 
     */
    public PersonEnglishStructuredNameGivenNameV10CT createPersonEnglishStructuredNameGivenNameV10CT() {
        return new PersonEnglishStructuredNameGivenNameV10CT();
    }

    /**
     * Create an instance of {@link PersonEnglishStructuredNamePersonNamePrefixTextV10CT }
     * 
     */
    public PersonEnglishStructuredNamePersonNamePrefixTextV10CT createPersonEnglishStructuredNamePersonNamePrefixTextV10CT() {
        return new PersonEnglishStructuredNamePersonNamePrefixTextV10CT();
    }

    /**
     * Create an instance of {@link PersonEnglishStructuredNamePersonNameSuffixTextV10CT }
     * 
     */
    public PersonEnglishStructuredNamePersonNameSuffixTextV10CT createPersonEnglishStructuredNamePersonNameSuffixTextV10CT() {
        return new PersonEnglishStructuredNamePersonNameSuffixTextV10CT();
    }

    /**
     * Create an instance of {@link PersonGenderCodeV10CT }
     * 
     */
    public PersonGenderCodeV10CT createPersonGenderCodeV10CT() {
        return new PersonGenderCodeV10CT();
    }

    /**
     * Create an instance of {@link HKIDNumberDetailsV10CT }
     * 
     */
    public HKIDNumberDetailsV10CT createHKIDNumberDetailsV10CT() {
        return new HKIDNumberDetailsV10CT();
    }

    /**
     * Create an instance of {@link HKIDNumberIdentifierV10CT }
     * 
     */
    public HKIDNumberIdentifierV10CT createHKIDNumberIdentifierV10CT() {
        return new HKIDNumberIdentifierV10CT();
    }

    /**
     * Create an instance of {@link HKIDNumberCheckDigitTextV10CT }
     * 
     */
    public HKIDNumberCheckDigitTextV10CT createHKIDNumberCheckDigitTextV10CT() {
        return new HKIDNumberCheckDigitTextV10CT();
    }

    /**
     * Create an instance of {@link HKSARGDepartmentCodeV10CT }
     * 
     */
    public HKSARGDepartmentCodeV10CT createHKSARGDepartmentCodeV10CT() {
        return new HKSARGDepartmentCodeV10CT();
    }

}
