//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:47:35 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccij2d;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * UID = COM000028, Dictionary Entry Name = Person English Structured Name. Person Name Prefix. Text,
 * 			An expression that precedes a person's English name for addressing that person.  This is commonly known as a person's title.  Any valid title expression is permitted.  If any of the following are used, then the value should conform to the following format: Mr, Mrs, Ms, Miss, Dr, Prof
 * 
 * <p>Java class for PersonEnglishStructuredNamePersonNamePrefixText.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonEnglishStructuredNamePersonNamePrefixText.V1.0.CT"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;restriction base="&lt;CCT&gt;Text.CT"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonEnglishStructuredNamePersonNamePrefixText.V1.0.CT", namespace = "PEN")
public class PersonEnglishStructuredNamePersonNamePrefixTextV10CT
    extends TextCT
{


}
