//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:47:35 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccij2d;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * a specific character string used to identify a type of XML message - Message ID
 * 				1) CM-GI01 : Summons Application
 * 				2) CM-GI02 : Summons Allocation
 * 				3) CM-GI03 : Court Result
 * 				4) CM-GI04 : Appeal Review Grant
 * 				5) CM-GI05 : Warrant Status Update
 * 				6) CM-GI06 : Witness Summons Application
 * 				7) CM-GI07 : Witness Summons Allocation
 * 				8) CM-GI08 : Latest Defendant Residential Address
 * 				9) CM-GI09 : Future Hearing Allocation
 * 				10)CM-GI10 : Reservice Result
 * 				11)CM-GI11 : Payment
 * 				12)CM-GI12 : SOD Application
 * 				13)CM-GI13 : SOD Application Result
 * 				14)CM-GI14 : Departmental Notice Application
 * 				15)CM-GI15 : Departmental Notice Allocation Result
 * 				16)CM-GI16 : Departmental Notice Hearing Result
 * 	    	    17)CM-FP01 : Fixed Penalty Notice of Order Application
 * 	            18)CM-FP02 : Fixed Penalty Summons Application
 * 	            19)CM-G03  : Witness Summons Application
 * 	            21)CM-FP04 : Notice of Order/ Summons Hearing Allocation Result
 * 	            22)CM-FP05 : Fixed Penalty Notice of Order Hearing Result
 * 	            23)CM-FP06 : Fixed Penalty Summons Hearing Result
 * 	            24)CM-G04  : Witness Summons Allocation Result
 * 	            25)CM-FP08 : Appeal/ Review Filing Interface
 * 	            26)CM-G05  : Warrant Status Change Notification
 * 				27)CM-G06  : Court Payment Interface
 * 				28)CM-FP10 : Fixed Penalty Distress Warrant Application
 * 				29)CM-FP11 : Distress Warrant Application Result
 * 				30)CM-FP12 : Distress Warrant Status Change
 * 				31)CM-FP13 : Court Payment for Distress Warrant Costs
 *                                 32)CM-CC01 : Charge Case Application
 *                                 33)CM-CC02 : Charge Case Allocation
 *                                 34)CM-GI17 : Case Document Submission
 *                                 35)CM-GI18 : Case Document Acknowledgement
 *                                 36)CM-CC03 : Case Amendment Application
 *                                 37)CM-CC04 : Case Amendment Result
 *                                 38)CM-CC05 : Bail Register
 *                                 39)CM-CC06 : Charge Case Hearing Result
 *                                 40)CM-GI19 : Court Document
 *                                 41)CM-GI20 : SOD Details Update
 * 			
 * 
 * <p>Java class for Prefix.V1.3.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Prefix.V1.3.CT"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;restriction base="&lt;CCT&gt;Code.CT"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Prefix.V1.3.CT")
public class PrefixV13CT
    extends CodeCT
{


}
