//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.29 at 10:40:40 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gdsid2j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * appeal details consists of 
 *                                a) Case Number Object
 *                                b) Appeal Internal Number
 *                                c) Appeal Register Serial Number
 *                                d) Filing Date
 *                                e) Applied Party 
 *             
 * 
 * <p>Java class for Appeal.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Appeal.V1.0.CT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CaseNumber" type="{}CaseNumber.V1.0.CT"/>
 *         &lt;element name="AppealInternalNumber" type="{}AppealInternalNumber.V1.0.CT"/>
 *         &lt;element name="AppealRegisterNumber" type="{}AppealRegisterNumber.V1.0.CT" minOccurs="0"/>
 *         &lt;element name="FilingDate" type="{CCT}Date.CT"/>
 *         &lt;element name="AppliedParty" type="{}AppealAppliedParty.V1.0.CT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Appeal.V1.0.CT", propOrder = {
    "caseNumber",
    "appealInternalNumber",
    "appealRegisterNumber",
    "filingDate",
    "appliedParty"
})
public class AppealV10CT {

    @XmlElement(name = "CaseNumber", required = true)
    protected CaseNumberV10CT caseNumber;
    @XmlElement(name = "AppealInternalNumber", required = true)
    protected AppealInternalNumberV10CT appealInternalNumber;
    @XmlElement(name = "AppealRegisterNumber")
    protected AppealRegisterNumberV10CT appealRegisterNumber;
    @XmlElement(name = "FilingDate", required = true)
    protected DateCT filingDate;
    @XmlElement(name = "AppliedParty", required = true)
    protected AppealAppliedPartyV10CT appliedParty;

    /**
     * Gets the value of the caseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link CaseNumberV10CT }
     *     
     */
    public CaseNumberV10CT getCaseNumber() {
        return caseNumber;
    }

    /**
     * Sets the value of the caseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseNumberV10CT }
     *     
     */
    public void setCaseNumber(CaseNumberV10CT value) {
        this.caseNumber = value;
    }

    /**
     * Gets the value of the appealInternalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link AppealInternalNumberV10CT }
     *     
     */
    public AppealInternalNumberV10CT getAppealInternalNumber() {
        return appealInternalNumber;
    }

    /**
     * Sets the value of the appealInternalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppealInternalNumberV10CT }
     *     
     */
    public void setAppealInternalNumber(AppealInternalNumberV10CT value) {
        this.appealInternalNumber = value;
    }

    /**
     * Gets the value of the appealRegisterNumber property.
     * 
     * @return
     *     possible object is
     *     {@link AppealRegisterNumberV10CT }
     *     
     */
    public AppealRegisterNumberV10CT getAppealRegisterNumber() {
        return appealRegisterNumber;
    }

    /**
     * Sets the value of the appealRegisterNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppealRegisterNumberV10CT }
     *     
     */
    public void setAppealRegisterNumber(AppealRegisterNumberV10CT value) {
        this.appealRegisterNumber = value;
    }

    /**
     * Gets the value of the filingDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getFilingDate() {
        return filingDate;
    }

    /**
     * Sets the value of the filingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setFilingDate(DateCT value) {
        this.filingDate = value;
    }

    /**
     * Gets the value of the appliedParty property.
     * 
     * @return
     *     possible object is
     *     {@link AppealAppliedPartyV10CT }
     *     
     */
    public AppealAppliedPartyV10CT getAppliedParty() {
        return appliedParty;
    }

    /**
     * Sets the value of the appliedParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppealAppliedPartyV10CT }
     *     
     */
    public void setAppliedParty(AppealAppliedPartyV10CT value) {
        this.appliedParty = value;
    }

}
