//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:51:00 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccid2j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * bail (Pol.40) details consists of 
 *                                a) Bail Book Serial Number (Pol.40 no.)
 *                                b) Bail Amount (in HKD)
 * 			
 * 
 * <p>Java class for BailPol40.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BailPol40.V1.0.CT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BailBookSerialNumber" type="{}BailBookSerialNumber.V1.0.CT"/&gt;
 *         &lt;element name="BailAmount" type="{}Amount.V1.0.CT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BailPol40.V1.0.CT", propOrder = {
    "bailBookSerialNumber",
    "bailAmount"
})
public class BailPol40V10CT {

    @XmlElement(name = "BailBookSerialNumber", required = true)
    protected BailBookSerialNumberV10CT bailBookSerialNumber;
    @XmlElement(name = "BailAmount", required = true)
    protected AmountV10CT bailAmount;

    /**
     * Gets the value of the bailBookSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BailBookSerialNumberV10CT }
     *     
     */
    public BailBookSerialNumberV10CT getBailBookSerialNumber() {
        return bailBookSerialNumber;
    }

    /**
     * Sets the value of the bailBookSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BailBookSerialNumberV10CT }
     *     
     */
    public void setBailBookSerialNumber(BailBookSerialNumberV10CT value) {
        this.bailBookSerialNumber = value;
    }

    /**
     * Gets the value of the bailAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountV10CT }
     *     
     */
    public AmountV10CT getBailAmount() {
        return bailAmount;
    }

    /**
     * Sets the value of the bailAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountV10CT }
     *     
     */
    public void setBailAmount(AmountV10CT value) {
        this.bailAmount = value;
    }

}
