//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:51:00 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccid2j;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  Charge Case Amendment Application Message
 *                               Derived from Case.V1.0.CT
 *                               Extension consists of
 * 								a) Record Prefix
 * 								b) Amendment Reference Number
 * 								c) Amendment Details Object
 * 								d) Offence Amendment Details Object
 * 								e) Defendant Amendment Details Object
 * 								f) Bail Remand Amendment Details Object
 * 								g) Surety Amendment Details Object
 *                                 h) Witness Amendment Details Object
 * 			
 * 
 * <p>Java class for ChargeCaseAmendment.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChargeCaseAmendment.V1.0.CT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}Case.V1.0.CT"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RecordPrefix" type="{}Prefix.V1.3.CT"/&gt;
 *         &lt;element name="AmendmentReferenceNumber" type="{}AmendmentReferenceNumber.V1.0.CT"/&gt;
 *         &lt;element name="GeneralAmendment" type="{}CommonAmendment.V1.0.CT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="OffenceAmendment" type="{}OffenceAmendment.V1.0.CT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DefendantAmendment" type="{}DefendantAmendment.V1.0.CT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="BailRemandAmendment" type="{}BailRemandAmendment.V1.0.CT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SuretyAmendment" type="{}SuretyAmendment.V1.0.CT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="WitnessAmendment" type="{}WitnessAmendment.V1.0.CT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChargeCaseAmendment.V1.0.CT", propOrder = {
    "recordPrefix",
    "amendmentReferenceNumber",
    "generalAmendment",
    "offenceAmendment",
    "defendantAmendment",
    "bailRemandAmendment",
    "suretyAmendment",
    "witnessAmendment"
})
public class ChargeCaseAmendmentV10CT
    extends CaseV10CT
{

    @XmlElement(name = "RecordPrefix", required = true)
    protected PrefixV13CT recordPrefix;
    @XmlElement(name = "AmendmentReferenceNumber", required = true)
    protected AmendmentReferenceNumberV10CT amendmentReferenceNumber;
    @XmlElement(name = "GeneralAmendment")
    protected List<CommonAmendmentV10CT> generalAmendment;
    @XmlElement(name = "OffenceAmendment")
    protected List<OffenceAmendmentV10CT> offenceAmendment;
    @XmlElement(name = "DefendantAmendment")
    protected List<DefendantAmendmentV10CT> defendantAmendment;
    @XmlElement(name = "BailRemandAmendment")
    protected List<BailRemandAmendmentV10CT> bailRemandAmendment;
    @XmlElement(name = "SuretyAmendment")
    protected List<SuretyAmendmentV10CT> suretyAmendment;
    @XmlElement(name = "WitnessAmendment")
    protected List<WitnessAmendmentV10CT> witnessAmendment;

    /**
     * Gets the value of the recordPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link PrefixV13CT }
     *     
     */
    public PrefixV13CT getRecordPrefix() {
        return recordPrefix;
    }

    /**
     * Sets the value of the recordPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefixV13CT }
     *     
     */
    public void setRecordPrefix(PrefixV13CT value) {
        this.recordPrefix = value;
    }

    /**
     * Gets the value of the amendmentReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentReferenceNumberV10CT }
     *     
     */
    public AmendmentReferenceNumberV10CT getAmendmentReferenceNumber() {
        return amendmentReferenceNumber;
    }

    /**
     * Sets the value of the amendmentReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentReferenceNumberV10CT }
     *     
     */
    public void setAmendmentReferenceNumber(AmendmentReferenceNumberV10CT value) {
        this.amendmentReferenceNumber = value;
    }

    /**
     * Gets the value of the generalAmendment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalAmendment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneralAmendment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommonAmendmentV10CT }
     * 
     * 
     */
    public List<CommonAmendmentV10CT> getGeneralAmendment() {
        if (generalAmendment == null) {
            generalAmendment = new ArrayList<CommonAmendmentV10CT>();
        }
        return this.generalAmendment;
    }

    /**
     * Gets the value of the offenceAmendment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offenceAmendment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffenceAmendment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OffenceAmendmentV10CT }
     * 
     * 
     */
    public List<OffenceAmendmentV10CT> getOffenceAmendment() {
        if (offenceAmendment == null) {
            offenceAmendment = new ArrayList<OffenceAmendmentV10CT>();
        }
        return this.offenceAmendment;
    }

    /**
     * Gets the value of the defendantAmendment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defendantAmendment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefendantAmendment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefendantAmendmentV10CT }
     * 
     * 
     */
    public List<DefendantAmendmentV10CT> getDefendantAmendment() {
        if (defendantAmendment == null) {
            defendantAmendment = new ArrayList<DefendantAmendmentV10CT>();
        }
        return this.defendantAmendment;
    }

    /**
     * Gets the value of the bailRemandAmendment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bailRemandAmendment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBailRemandAmendment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BailRemandAmendmentV10CT }
     * 
     * 
     */
    public List<BailRemandAmendmentV10CT> getBailRemandAmendment() {
        if (bailRemandAmendment == null) {
            bailRemandAmendment = new ArrayList<BailRemandAmendmentV10CT>();
        }
        return this.bailRemandAmendment;
    }

    /**
     * Gets the value of the suretyAmendment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the suretyAmendment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuretyAmendment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuretyAmendmentV10CT }
     * 
     * 
     */
    public List<SuretyAmendmentV10CT> getSuretyAmendment() {
        if (suretyAmendment == null) {
            suretyAmendment = new ArrayList<SuretyAmendmentV10CT>();
        }
        return this.suretyAmendment;
    }

    /**
     * Gets the value of the witnessAmendment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the witnessAmendment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWitnessAmendment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WitnessAmendmentV10CT }
     * 
     * 
     */
    public List<WitnessAmendmentV10CT> getWitnessAmendment() {
        if (witnessAmendment == null) {
            witnessAmendment = new ArrayList<WitnessAmendmentV10CT>();
        }
        return this.witnessAmendment;
    }

}
