//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 04:51:00 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gccid2j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Basic amendment object consists of
 * 						a) Action
 * 						b) Data Name
 * 						c) Data Value
 * 			
 * 
 * <p>Java class for CommonAmendment.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonAmendment.V1.0.CT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Action" type="{}AmendmentAction.V1.0.CT"/&gt;
 *         &lt;element name="DataName" type="{}AmendmentDataName.V1.0.CT"/&gt;
 *         &lt;element name="DataValue" type="{}AmendmentDataValue.V1.0.CT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonAmendment.V1.0.CT", propOrder = {
    "action",
    "dataName",
    "dataValue"
})
@XmlSeeAlso({
    OffenceAmendmentV10CT.class,
    DefendantAmendmentV10CT.class,
    WitnessAmendmentV10CT.class,
    SuretyAmendmentV10CT.class,
    BailRemandAmendmentV10CT.class
})
public class CommonAmendmentV10CT {

    @XmlElement(name = "Action", required = true)
    protected AmendmentActionV10CT action;
    @XmlElement(name = "DataName", required = true)
    protected AmendmentDataNameV10CT dataName;
    @XmlElement(name = "DataValue", required = true)
    protected AmendmentDataValueV10CT dataValue;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentActionV10CT }
     *     
     */
    public AmendmentActionV10CT getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentActionV10CT }
     *     
     */
    public void setAction(AmendmentActionV10CT value) {
        this.action = value;
    }

    /**
     * Gets the value of the dataName property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentDataNameV10CT }
     *     
     */
    public AmendmentDataNameV10CT getDataName() {
        return dataName;
    }

    /**
     * Sets the value of the dataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentDataNameV10CT }
     *     
     */
    public void setDataName(AmendmentDataNameV10CT value) {
        this.dataName = value;
    }

    /**
     * Gets the value of the dataValue property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentDataValueV10CT }
     *     
     */
    public AmendmentDataValueV10CT getDataValue() {
        return dataValue;
    }

    /**
     * Sets the value of the dataValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentDataValueV10CT }
     *     
     */
    public void setDataValue(AmendmentDataValueV10CT value) {
        this.dataValue = value;
    }

}
