//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.03 at 10:31:06 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gdsnid2j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Bail Remand amendment object
 * 							Derived from CommonAmendment.V1.0.CT
 * 							Extension consists of
 * 							a) Bail Remand Identifier
 * 			
 * 
 * <p>Java class for BailRemandAmendment.V1.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BailRemandAmendment.V1.0.CT">
 *   &lt;complexContent>
 *     &lt;extension base="{}CommonAmendment.V1.0.CT">
 *       &lt;sequence>
 *         &lt;element name="BailRemandIdentifier" type="{}BailRemandIdentifier.V1.0.CT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BailRemandAmendment.V1.0.CT", propOrder = {
    "bailRemandIdentifier"
})
public class BailRemandAmendmentV10CT
    extends CommonAmendmentV10CT
{

    @XmlElement(name = "BailRemandIdentifier", required = true)
    protected BailRemandIdentifierV10CT bailRemandIdentifier;

    /**
     * Gets the value of the bailRemandIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BailRemandIdentifierV10CT }
     *     
     */
    public BailRemandIdentifierV10CT getBailRemandIdentifier() {
        return bailRemandIdentifier;
    }

    /**
     * Sets the value of the bailRemandIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BailRemandIdentifierV10CT }
     *     
     */
    public void setBailRemandIdentifier(BailRemandIdentifierV10CT value) {
        this.bailRemandIdentifier = value;
    }

}
