//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.03 at 10:31:06 AM CST 
//


package hk.judiciary.icmsint.model.sysinf.inf.gdsnid2j;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Fixed Penalty Summons message consists of 
 * 					a) Record Prefix
 * 					b) Case Number Object
 * 					c) Prosecution Department Code
 * 					d) Demand Note Number
 * 					e) Demand Note Issue Date
 * 					f) FPN Dispute Date								
 * 					g) Manual Schedule Indicator
 * 					h) Informant Details
 * 					i) Defendant Details
 * 					j) SOD Details
 * 					k) Case Offence
 * 					l) Dispute from Notice of Order 
 * 					m) Rescind to Dispute Order Date
 * 					n) Additional Section
 * 					o) Preferred Warrant Type
 *                                         p) Offence Variable Object(s)
 *                                         q) Fixed Penalty Application Nature
 * 			
 * 
 * <p>Java class for FixedPenaltySummons.V2.0.CT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FixedPenaltySummons.V2.0.CT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecordPrefix" type="{}Prefix.V1.3.CT"/>
 *         &lt;element name="CaseNumber" type="{}CaseNumber.V1.0.CT"/>
 *         &lt;element name="ProsecutionDepartmentCode" type="{}ProsecutionDepartmentCode.V1.1.CT"/>
 *         &lt;element name="DemandNoteNumber" type="{}DemandNoteNumber.V1.1.CT"/>
 *         &lt;element name="DemandNoteIssueDate" type="{CCT}Date.CT"/>
 *         &lt;element name="FPNDisputeDate" type="{CCT}Date.CT" minOccurs="0"/>
 *         &lt;element name="ManualScheduleIndicator" type="{}FieldIndicator.V1.0.CT"/>
 *         &lt;element name="InformantDetails" type="{}Informant.V1.2.CT"/>
 *         &lt;element name="DefendantDetails" type="{}Defendant.V1.3.CT"/>
 *         &lt;element name="CaseSODDetails" type="{}CaseSOD.V1.2.CT"/>
 *         &lt;choice>
 *           &lt;element name="CaseOffence" type="{}CaseOffence.V1.0.CT"/>
 *           &lt;element name="CaseOffenceExtended" type="{}CaseOffence.V1.1.CT"/>
 *         &lt;/choice>
 *         &lt;element name="DisputeFromNoticeOfOrder" type="{}FieldIndicator.V1.0.CT"/>
 *         &lt;element name="RescindToDisputeOrderDate" type="{CCT}Date.CT" minOccurs="0"/>
 *         &lt;element name="RescindToDisputeOrderTime" type="{CCT}Time.CT" minOccurs="0"/>
 *         &lt;element name="AdditionalSection" type="{}AdditionalSection.V1.0.CT" minOccurs="0"/>
 *         &lt;element name="PreferredWarrantType" type="{}PreferredWarrantType.V1.0.CT" minOccurs="0"/>
 *         &lt;element name="OffenceVariable" type="{}OffenceVariable.V1.0.CT" maxOccurs="52" minOccurs="0"/>
 *         &lt;element name="FixedPenaltyApplicationNature" type="{}FixedPenaltyApplicationNature.V1.0.CT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FixedPenaltySummons.V2.0.CT", propOrder = {
    "recordPrefix",
    "caseNumber",
    "prosecutionDepartmentCode",
    "demandNoteNumber",
    "demandNoteIssueDate",
    "fpnDisputeDate",
    "manualScheduleIndicator",
    "informantDetails",
    "defendantDetails",
    "caseSODDetails",
    "caseOffence",
    "caseOffenceExtended",
    "disputeFromNoticeOfOrder",
    "rescindToDisputeOrderDate",
    "rescindToDisputeOrderTime",
    "additionalSection",
    "preferredWarrantType",
    "offenceVariable",
    "fixedPenaltyApplicationNature"
})
public class FixedPenaltySummonsV20CT {

    @XmlElement(name = "RecordPrefix", required = true)
    protected PrefixV13CT recordPrefix;
    @XmlElement(name = "CaseNumber", required = true)
    protected CaseNumberV10CT caseNumber;
    @XmlElement(name = "ProsecutionDepartmentCode", required = true)
    protected ProsecutionDepartmentCodeV11CT prosecutionDepartmentCode;
    @XmlElement(name = "DemandNoteNumber", required = true)
    protected DemandNoteNumberV11CT demandNoteNumber;
    @XmlElement(name = "DemandNoteIssueDate", required = true)
    protected DateCT demandNoteIssueDate;
    @XmlElement(name = "FPNDisputeDate")
    protected DateCT fpnDisputeDate;
    @XmlElement(name = "ManualScheduleIndicator", required = true)
    protected FieldIndicatorV10CT manualScheduleIndicator;
    @XmlElement(name = "InformantDetails", required = true)
    protected InformantV12CT informantDetails;
    @XmlElement(name = "DefendantDetails", required = true)
    protected DefendantV13CT defendantDetails;
    @XmlElement(name = "CaseSODDetails", required = true)
    protected CaseSODV12CT caseSODDetails;
    @XmlElement(name = "CaseOffence")
    protected CaseOffenceV10CT caseOffence;
    @XmlElement(name = "CaseOffenceExtended")
    protected CaseOffenceV11CT caseOffenceExtended;
    @XmlElement(name = "DisputeFromNoticeOfOrder", required = true)
    protected FieldIndicatorV10CT disputeFromNoticeOfOrder;
    @XmlElement(name = "RescindToDisputeOrderDate")
    protected DateCT rescindToDisputeOrderDate;
    @XmlElement(name = "RescindToDisputeOrderTime")
    protected TimeCT rescindToDisputeOrderTime;
    @XmlElement(name = "AdditionalSection")
    protected AdditionalSectionV10CT additionalSection;
    @XmlElement(name = "PreferredWarrantType")
    protected PreferredWarrantTypeV10CT preferredWarrantType;
    @XmlElement(name = "OffenceVariable")
    protected List<OffenceVariableV10CT> offenceVariable;
    @XmlElement(name = "FixedPenaltyApplicationNature", required = true)
    protected FixedPenaltyApplicationNatureV10CT fixedPenaltyApplicationNature;

    /**
     * Gets the value of the recordPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link PrefixV13CT }
     *     
     */
    public PrefixV13CT getRecordPrefix() {
        return recordPrefix;
    }

    /**
     * Sets the value of the recordPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefixV13CT }
     *     
     */
    public void setRecordPrefix(PrefixV13CT value) {
        this.recordPrefix = value;
    }

    /**
     * Gets the value of the caseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link CaseNumberV10CT }
     *     
     */
    public CaseNumberV10CT getCaseNumber() {
        return caseNumber;
    }

    /**
     * Sets the value of the caseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseNumberV10CT }
     *     
     */
    public void setCaseNumber(CaseNumberV10CT value) {
        this.caseNumber = value;
    }

    /**
     * Gets the value of the prosecutionDepartmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProsecutionDepartmentCodeV11CT }
     *     
     */
    public ProsecutionDepartmentCodeV11CT getProsecutionDepartmentCode() {
        return prosecutionDepartmentCode;
    }

    /**
     * Sets the value of the prosecutionDepartmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProsecutionDepartmentCodeV11CT }
     *     
     */
    public void setProsecutionDepartmentCode(ProsecutionDepartmentCodeV11CT value) {
        this.prosecutionDepartmentCode = value;
    }

    /**
     * Gets the value of the demandNoteNumber property.
     * 
     * @return
     *     possible object is
     *     {@link DemandNoteNumberV11CT }
     *     
     */
    public DemandNoteNumberV11CT getDemandNoteNumber() {
        return demandNoteNumber;
    }

    /**
     * Sets the value of the demandNoteNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandNoteNumberV11CT }
     *     
     */
    public void setDemandNoteNumber(DemandNoteNumberV11CT value) {
        this.demandNoteNumber = value;
    }

    /**
     * Gets the value of the demandNoteIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getDemandNoteIssueDate() {
        return demandNoteIssueDate;
    }

    /**
     * Sets the value of the demandNoteIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setDemandNoteIssueDate(DateCT value) {
        this.demandNoteIssueDate = value;
    }

    /**
     * Gets the value of the fpnDisputeDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getFPNDisputeDate() {
        return fpnDisputeDate;
    }

    /**
     * Sets the value of the fpnDisputeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setFPNDisputeDate(DateCT value) {
        this.fpnDisputeDate = value;
    }

    /**
     * Gets the value of the manualScheduleIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getManualScheduleIndicator() {
        return manualScheduleIndicator;
    }

    /**
     * Sets the value of the manualScheduleIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setManualScheduleIndicator(FieldIndicatorV10CT value) {
        this.manualScheduleIndicator = value;
    }

    /**
     * Gets the value of the informantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InformantV12CT }
     *     
     */
    public InformantV12CT getInformantDetails() {
        return informantDetails;
    }

    /**
     * Sets the value of the informantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformantV12CT }
     *     
     */
    public void setInformantDetails(InformantV12CT value) {
        this.informantDetails = value;
    }

    /**
     * Gets the value of the defendantDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DefendantV13CT }
     *     
     */
    public DefendantV13CT getDefendantDetails() {
        return defendantDetails;
    }

    /**
     * Sets the value of the defendantDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefendantV13CT }
     *     
     */
    public void setDefendantDetails(DefendantV13CT value) {
        this.defendantDetails = value;
    }

    /**
     * Gets the value of the caseSODDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CaseSODV12CT }
     *     
     */
    public CaseSODV12CT getCaseSODDetails() {
        return caseSODDetails;
    }

    /**
     * Sets the value of the caseSODDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseSODV12CT }
     *     
     */
    public void setCaseSODDetails(CaseSODV12CT value) {
        this.caseSODDetails = value;
    }

    /**
     * Gets the value of the caseOffence property.
     * 
     * @return
     *     possible object is
     *     {@link CaseOffenceV10CT }
     *     
     */
    public CaseOffenceV10CT getCaseOffence() {
        return caseOffence;
    }

    /**
     * Sets the value of the caseOffence property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseOffenceV10CT }
     *     
     */
    public void setCaseOffence(CaseOffenceV10CT value) {
        this.caseOffence = value;
    }

    /**
     * Gets the value of the caseOffenceExtended property.
     * 
     * @return
     *     possible object is
     *     {@link CaseOffenceV11CT }
     *     
     */
    public CaseOffenceV11CT getCaseOffenceExtended() {
        return caseOffenceExtended;
    }

    /**
     * Sets the value of the caseOffenceExtended property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseOffenceV11CT }
     *     
     */
    public void setCaseOffenceExtended(CaseOffenceV11CT value) {
        this.caseOffenceExtended = value;
    }

    /**
     * Gets the value of the disputeFromNoticeOfOrder property.
     * 
     * @return
     *     possible object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public FieldIndicatorV10CT getDisputeFromNoticeOfOrder() {
        return disputeFromNoticeOfOrder;
    }

    /**
     * Sets the value of the disputeFromNoticeOfOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldIndicatorV10CT }
     *     
     */
    public void setDisputeFromNoticeOfOrder(FieldIndicatorV10CT value) {
        this.disputeFromNoticeOfOrder = value;
    }

    /**
     * Gets the value of the rescindToDisputeOrderDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCT }
     *     
     */
    public DateCT getRescindToDisputeOrderDate() {
        return rescindToDisputeOrderDate;
    }

    /**
     * Sets the value of the rescindToDisputeOrderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCT }
     *     
     */
    public void setRescindToDisputeOrderDate(DateCT value) {
        this.rescindToDisputeOrderDate = value;
    }

    /**
     * Gets the value of the rescindToDisputeOrderTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeCT }
     *     
     */
    public TimeCT getRescindToDisputeOrderTime() {
        return rescindToDisputeOrderTime;
    }

    /**
     * Sets the value of the rescindToDisputeOrderTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeCT }
     *     
     */
    public void setRescindToDisputeOrderTime(TimeCT value) {
        this.rescindToDisputeOrderTime = value;
    }

    /**
     * Gets the value of the additionalSection property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalSectionV10CT }
     *     
     */
    public AdditionalSectionV10CT getAdditionalSection() {
        return additionalSection;
    }

    /**
     * Sets the value of the additionalSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalSectionV10CT }
     *     
     */
    public void setAdditionalSection(AdditionalSectionV10CT value) {
        this.additionalSection = value;
    }

    /**
     * Gets the value of the preferredWarrantType property.
     * 
     * @return
     *     possible object is
     *     {@link PreferredWarrantTypeV10CT }
     *     
     */
    public PreferredWarrantTypeV10CT getPreferredWarrantType() {
        return preferredWarrantType;
    }

    /**
     * Sets the value of the preferredWarrantType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferredWarrantTypeV10CT }
     *     
     */
    public void setPreferredWarrantType(PreferredWarrantTypeV10CT value) {
        this.preferredWarrantType = value;
    }

    /**
     * Gets the value of the offenceVariable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offenceVariable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffenceVariable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OffenceVariableV10CT }
     * 
     * 
     */
    public List<OffenceVariableV10CT> getOffenceVariable() {
        if (offenceVariable == null) {
            offenceVariable = new ArrayList<OffenceVariableV10CT>();
        }
        return this.offenceVariable;
    }

    /**
     * Gets the value of the fixedPenaltyApplicationNature property.
     * 
     * @return
     *     possible object is
     *     {@link FixedPenaltyApplicationNatureV10CT }
     *     
     */
    public FixedPenaltyApplicationNatureV10CT getFixedPenaltyApplicationNature() {
        return fixedPenaltyApplicationNature;
    }

    /**
     * Sets the value of the fixedPenaltyApplicationNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedPenaltyApplicationNatureV10CT }
     *     
     */
    public void setFixedPenaltyApplicationNature(FixedPenaltyApplicationNatureV10CT value) {
        this.fixedPenaltyApplicationNature = value;
    }

}
